### ISSUE TITLE
Error while loading shared libraries on AppImage run

### ISSUE THREAD

**Issue by akontsevich** [AppImage/AppImageKit#1012]
Hi @TheAssassin and @probonopd. Have error with either `linuxdeploy` or `appimagetool` if I create AppImage in docker.

As You may remember I was able to build and run AppImage successfully under CentOS 7.x based docker image here: https://github.com/AppImage/AppImageKit/issues/998#issuecomment-543368166

However when we migrate to Ubuntu 18.04 and added `libgdal` and `boost` dependencies to the app some problems appeared with shared libraries on AppImage run:
```
error while loading shared libraries: <lib_name>: cannot open shared object file: 
No such file or directory
```

And this happens with tens or hundreds shared libraries so I can't solve the issue copying them manually to app lib dir like in the link [above](https://github.com/AppImage/AppImageKit/issues/998#issuecomment-543368166). So copying libraries like this:
```
# copy some missed libs to the bundle
libs=(libssl.so.1 libcrypto.so.1 libicui18n.so libicuuc.so libicudata.so \
     libgdal.so libarmadillo.so libproj.so libjson-c.so libqhull.so libwebp.so \
     libpoppler.so libepsilon.so libkmlbase.so libkmldom.so libkmlengine.so \
     libnetcdf.so libhdf5_serial.so libmfhdfalt.so libdfalt.so libogdi.so \
     libgeotiff.so libdapclient.so libdap.so libpcre.s)
for lib in "${libs[@]}"
do
    cp $(ldconfig -p | grep ${lib} | head -n1 | tr ' ' '\n' | grep /) ./$APP.AppDir/Qt/libs/    
done
```
does not work any more as there are too much libraries and previous 80 MB AppImage which worked everywhere grows now in more than 2 times and does not work. I saw `./linuxdeploy-x86_64.AppImage` output and it strips these libraries from final AppImage for some reason - see libs list above after adding `gdal` and `boost` (previously it was necessary to deploy manually only following `libssl.so.1, libcrypto.so.1, libicui18n.so, libicuuc.so, libicudata.so`).

See `./linuxdeploy-x86_64.AppImage` output: [appimage_bug.txt](https://github.com/probonopd/linuxdeployqt/files/3903099/appimage_bug.txt)

After `linuxdeploy` I've tried Your tool - `appimagetool` and got almost same results: gdal and other libraries are not included in docker build so AppImage does not work. Outside docker - all builds and works fine, however have size: ~ 320 MB with Your tool.

Will try now https://github.com/probonopd/linuxdeployqt as well. However afraid result will be the same.

Any ideas? What the problem could be, how to solve? Thanks!

**Comment by TheAssassin** [comment]
Please open an issue over at linuxdeploy.

appimagetool doesn't bundle anything, so the issue is in the wrong place here.

Both linuxdeploy and @probonopd's tool use the same [excludelist](https://github.com/AppImage/pkg2appimage/blob/master/excludelist) which defines a list of library which should not end up in an AppImage. There's many reasons, one is that they can cause breakages, one is that there might be security issues (*looking at libssl!*) if they're never updated, another one is that they're usually bloat.

I don't know why libpoppler etc. (they're not on the excludelist!) are not bundled, but as said, please open an issue at linuxdeploy's tracker, and I'll have a look.

By the way, neither of the tools *strips* any files from the AppImage (only know for sure for linuxdeploy, though). They just don't bundle them. If you copy them manually beforehand, they won't be removed. But that doesn't mean it's a good idea to do so.

**Comment by akontsevich** [comment]
I opened it correctly as Your `appimagetool` does not work for me. `linuxdeploy` is just an example and not supported any more and outdated.

**Comment by akontsevich** [comment]
>appimagetool doesn't bundle anything, so the issue is in the wrong place here.

What do You mean?! I mean I use Your `./appimagetool-x86_64.AppImage` which creates AppImage for me.

>  If you copy them manually beforehand, they won't be removed. But that doesn't mean it's a good idea to do so.

Yes, not good idea, so I do not want to do so.

**Comment by akontsevich** [comment]
I use this: 

![Screenshot_20191130_013739](https://user-images.githubusercontent.com/3843657/69892795-03a97e00-1312-11ea-8b0e-b33e3fc8106f.png)

Why You are saying it is the wrong place?!

**Comment by TheAssassin** [comment]
Calm down, buddy. You don't have to mail me, just because I leave my workstation for 10 minutes.

So, let me tell you about my assumptions

1. It seems that you just ran appimagetool on an AppDir you previously had run linuxdeploy on.
2. You seem to have expected appimagetool to do things it doesn't do: appimagetool just "converts" an AppDir into an AppImage, it doesn't bundle additional files. It never has, it never will.
3. It does seem you have not understood the relation between the tools linuxdeploy, linuxdeployqt and appimagetool.

This is what I understood: You are unhappy because linuxdeploy has not bundled libraries your app requires (through `dlopen` or something), which means that when you run the resulting AppImage, your app shows error messages.

If that's correct so far, your issue is related to the *bundling of libraries*, not the creation of an AppImage.

linuxdeploy[qt] both use appimagetool to make AppImages, but only for that. Everything else is not related to appimagetool. And your problem isn't that you can't make an AppImage, it's that your AppImage doesn't contain some files.

Your problem therefore falls into the "jurisdiction" of linuxdeploy, you probably want to open a feature request or bug report over there. There is the place to help you. I would've explained you what an excludelist is, why we use it and why linuxdeploy does skip some files during bundling. Furthermore, I would've explained you, as detailed as required, why we cannot automatically detect stuff that is `dlopen`ed by an app. There are ways to solve this, e.g., we have a plugin that bundles Qt plugins (and their dependencies are often `dlopen`ed), but, as shown in that linuxdeploy-plugin-qt, this requires some annoying "if this then that" kind of code that is aware of which dependencies plugins need, no autodetection is involved.

Therefore, your issue should also be titled, "AppImage lacks libraries dlopened by app" or so.

Please don't be aggressive, that is counterproductive.

> linuxdeploy is just an example and not supported any more and outdated.

I have no idea what this is supposed to mean. linuxdeploy is an alive project, there are regular commits, it isn't outdated, actually it's the most state-of-the-art tool you'll find to create AppDirs with and automatically put libraries and other files into them.

**Comment by akontsevich** [comment]
> Calm down, buddy. You don't have to mail me, just because I leave my workstation for 10 minutes.

Sorry, probonopd just ignored my further questions, just stereotype.

>  3. It does seem you have not understood the relation between the tools linuxdeploy, linuxdeployqt and appimagetool.

Exactly, did not need that - just create working AppImage. :wink: 

> no autodetection is involved.

Bad, I thought it is.

> Therefore, your issue should also be titled, "AppImage lacks libraries dlopened by app" or so.

Ok, np, was too deeply for my current understanding.
 
> Please don't be aggressive, that is counterproductive.

I'm not at all! :smile: :wink: 

> > linuxdeploy is just an example and not supported any more and outdated.
> 
> I have no idea what this is supposed to mean. linuxdeploy is an alive project, there are regular commits, it isn't outdated, actually it's the most state-of-the-art tool you'll find to create AppDirs with and automatically put libraries and other files into them.

I mean that repo: https://github.com/ribtoks/linuxdeploy - which I came from https://github.com/probonopd/linuxdeploy - was lost in Yours `linuxdeploy`s :wink:

**Comment by TheAssassin** [comment]
Forgot to post a link to the tracker, it seems? Sorry. My bad!
