### ISSUE TITLE
"appimagekit-" prefix on icon names

### ISSUE THREAD

**Issue by creepertron95** [AppImage/AppImageKit#1026]
I was wanting to ask about the icon names of Appimages.

I was wondering why would there be a `appimagekit-` prefix on the icon names instead of using the upstream icon name on the desktop files installed via AppImage or hardcoding the icon names found on the desktop files? 

 I was looking through an issue of the Numix icon theme: https://github.com/numixproject/numix-core/issues/3702#issuecomment-310211829

**Comment by probonopd** [comment]
If I remember correctly we did this so that the application icon inside the AppImage cannot be overridden by themes installed in the system.

We want the creator of an AppImage to be in full control over which icon gets shown in the end, not the icon themes installed on the system. Example:

![](https://user-images.githubusercontent.com/2480569/42704269-bf0ec010-86be-11e8-846d-95dfa034a451.png)
