### ISSUE TITLE
Need a way to name the final output file [Feature Request]

### ISSUE THREAD

**Issue by Light-Wizzard** [AppImage/AppImageKit#1040]
This is in regards to this issue in LinuxDeployQt:
https://github.com/probonopd/linuxdeployqt/issues/432

My question is, does appimagetool have a way to rename or name an AppImage, in other words, does it have a way to pass in a name, without it adding version or platform information, such that it uses only the name of the file in the desktop file it is feed in?

Or is there a way to modify as I preposed in LinuxDeployQt issue 432, and are you willing to add this feature, not really one question.

My problem, if you do not get it from the above, is that I want to use zsync, but I also want to be able to name my files in advance and just do a continuous update, and I do not want the platform or version number injected into the name, so my project is more portable across platforms, and I cannot just rename the file, that breaks the zsync link.

It seems most people just use a * to deal with it, it seems there has to be a better option since this does not work well with static string data used in links and requires me to make the files on the fly, and I am trying to do this in Travis, and it would just be nice to be able to control the file name, without the ugly platform or version numbers in it, but since both files are linked, it needs to done at the creation level, so it takes both projects to make this change.

Thanks

**Comment by probonopd** [comment]
Hi @Light-Wizzard 

```
export VERSION=somethingstatic
```

... then do as usual

**Comment by TheAssassin** [comment]
> If you cannot do this, then never rename, always build the AppImage with the right name from the beginning. To get rid of the variable version number just replace it with something static:
> 
> export VERSION=staticstring

appimagetool has always supported a second positional parameter which defines the output filename. If it is not provided, appimagetool guessifies something based on the desktop file *and* `$VERSION`.

https://github.com/linuxdeploy/linuxdeploy-plugin-appimage for example provides a way to overwrite the output filename using an environment variable called `$OUTPUT`. Internally all this does is pass a second parameter to appimagetool.

What you suggested is kind of worse than using a static filename, because `$VERSION` and the second parameter to appimagetool can actually be combined. That way, you have an AppImage with a predictable name *but containing version information*. If you just set `$VERSION` to some static string, you have a hackish workaround to get a static filename, and you sacrifice desktop integration versioning...

**Comment by Light-Wizzard** [comment]
Thanks for the info, I understand, --output may have been removed, I put in an issue, I will try the export.
export VERSION=travis
Just to be clear, you show pointing to the desktop or file, my guess is desktop is preferable if I add the exe name appname-travis-x86_64.AppImage, and from what I get, it uses the Name in the desktop file to create the name, there is also a GenericName, not sure how that is used, the extra stuff -travis-x86_64.AppImage does not get appended to the name, I guess it knows not to do that.

This is confusing without a good example, I also want to use AppImage Update, so I have to figure out the update-information variables, and figure out how that works, and do I need to add anything to my app to get that to work?

I want to make sure what I do does not mess up the Update, and I have no idea how to use that yet, do you have any examples?

Thanks, you can close both issues.

**Comment by Light-Wizzard** [comment]
Sorry about the confusion, I had no idea that linuxdeploy and probonopd were two different repos, so I was mixing the two together, and now that I understand both, I am not confused about it, but that was the source of my wanting to be able to name it, it seemed out of control with conflicting information, when it was me mixing the two.
