### ISSUE TITLE
Publish the validate tool binaries

### ISSUE THREAD

**Issue by azubieta** [AppImage/AppImageKit#1043]
There is a reference in the documentation to a tool called 'validate' but not links are provided provably it's because there are no binaries.

This tool seems to be important for AppImage users who want to validate their downloads, therefore it may be a good idea to publish it.

**Comment by probonopd** [comment]
Unfortunately the `validate` tool was not updated when some changes were introduced to the signing mechanism, and as a result, it is currently in a non-functional state. This is very unfortunate and any improvements would be appreciated.

cc @TheAssassin

**Comment by probonopd** [comment]
At this point, maybe it would be easiest to add a "validate" verb to [go-appimage](https://github.com/probonopd/go-appimage) (it already has the code for signing).

**Comment by azubieta** [comment]
Indeed it would be better it it becomes part of the go-appimage. Is there any ETA for go-appimage ? I mean for it to be the default.

**Comment by probonopd** [comment]
Once we are reasonably confident in it...

**Comment by ba32107** [comment]
Hi! Do I understand correctly that currently there's no way to easily sign and validate AppImages? My use-case is pretty simple: I want to sign my published AppImages in my CI pipeline and I want to offer an easy and straightforward way to my users to verify it.

**Comment by probonopd** [comment]
I think signing with https://github.com/AppImage/AppImageKit#appimagetool-usage `-s` works.

There is just currently no working `validate` binary, but tools like AppImageUpdate do verify signatures.

**Comment by ba32107** [comment]
Thanks - I guess it still makes sense to do the signatures, and at a later point I can include validation as well.

**Comment by Apfelwurm** [comment]
Hi, is there any progress here so far or is there any way how i can verify that my signing process works as its intended to?

**Comment by TheAssassin** [comment]
AppImageUpdate now provides a replacement for `validate.c` from this repository, implemented using the newly written validation code from its signing module. See https://github.com/AppImage/AppImageUpdate/releases/tag/continuous. This tool is significantly less error prone and eliminates the redundancy/code duplication between both repositories.

https://github.com/AppImage/AppImageUpdate/releases/tag/continuous

Note that validation here is just limited to "is this signed correctly". The tool does not provide any feedback whether updates would succeed. We could extend the tool, though, since that code can be extracted from the updater class.
