### ISSUE TITLE
README.md file incorrect

### ISSUE THREAD

**Issue by sk8nfool** [AppImage/AppImageKit#1047]
The instructions for building AppImageKit at the end of the README.md file don't match reality. The instructions say to 
```
git clone --single-branch --recursive https://github.com/AppImage/AppImageKit
cd AppImageKit/
sudo bash -ex install-build-deps.sh
bash -ex build.sh
```
Unfortunately there is no *install-build-deps.sh* file to execute.

**Comment by probonopd** [comment]
Hi @sk8nfool.
Generally we recommend to use our pre-compiled binaries, as we are specifically building them in a CentOS 6 container in order to increase compatibility even with older systems.

@TheAssassin do you know what happened to `install-build-deps.sh`? Are the currently correct instructions for building locally?

**Comment by TheAssassin** [comment]
The script was not only constantly out of date, but also very invasive and was likely to break people's setup. It's better not to have such scripts "hiding"/automating the installation. With `sudo` and `-y` here and there, you can easily eat up all space on a small SSD or otherwise break a system, etc. Therefore, this script was removed. 

We don't have a complete "setup script", as we have a mess of dependencies pulled in from various sources. However, our CMake scripts check for every single dependency and notice the user when something is missing, allowing them to `apt/yum/dnf/pkg install` that.

**Comment by sk8nfool** [comment]
Ah. So the script is supposed to be gone. That still means the instructions need to be fixed.

**Comment by probonopd** [comment]
@TheAssassin could you please give instructions? At this point I have to admit I wouldn't know how to build it locally without running from error to error.

**Comment by TheAssassin** [comment]
@sk8nfool yup, I'll be fixing that asap. @probonopd as said it's messy and complex and there can't be instructions for every distribution. A starting point can be our [Docker files in AppImageBuild](https://github.com/AppImage/AppImageBuild), which is our official collection of dependencies. You can even just use our Docker containers, they are built and stored on a container registry. The build script we use to make the AppImages is shipped in the [`travis/`](https://github.com/AppImage/AppImageKit/blob/master/travis/travis-build.sh) directory of this repository. However, that script is also trimmed on Travis CI and might not be safe to run locally. But you can also take this as inspiration.
