### ISSUE TITLE
Check kloudsec https hosting appimage.org

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#110]
https://kloudsec.com/github-pages/

Need to understand the security implications

**Comment by nubela** [comment]
Ok, product guy at Kloudsec reporting in!

* Kloudsec is a reverse proxy CDN, powered by an [Anycast architecture](https://blog.kloudsec.com/building-an-anycast-network/).
* This means by switching the custom domain to point to our IP, we'll proxy the request back to GH page if there are dynamic requests. Static assets are otherwise cached.
* Because we have control of the domain, we can provision LetsEncrypt certs by dynamically generating the specific challenge endpoints required by LetsEncrypt CA
* We then apply the SSL cert on all of our node locations (Singapore, US, and London, with more coming soon)
* We do not have full-stream encryption, mostly because GH does not support it

Happy to take on more questions on how it works!

**Comment by probonopd** [comment]
Also see #245

**Comment by probonopd** [comment]
https://kloudsec.com/ seems not reachable anymore.
