### ISSUE TITLE
Minimal distro capable to run appimage?

### ISSUE THREAD

**Issue by vinniec** [AppImage/AppImageKit#1142]
I've been trying to get vscodium to run on alpine for a while but I have not found any convenient solution.
One of these alternatives was to use appimage but it doesn't work since alpine uses musl instead of glibc.
So i thought to try with some other live distro to run when needed, I tried tinycore and it doesn't work, I tried slitaz and it doesn't work, (i would have tried easyos but the distro is experimental and doesn't start). I also had tails and I tried it, on tails the appimages work but it's not really the distro I would use for programming.
So I'm asking if anyone knows of a minimal distro that has only the essentials to run appimages and nothing more? I don't feel like launching a live ubuntu for this purpose.

**Comment by probonopd** [comment]
We are testing AppImages against the oldest still-supported LTS release of Ubuntu. So that should give the best results.

If your system has all of https://github.com/AppImage/pkg2appimage/blob/master/excludelist installed, then it should also work.

**Comment by bdantas** [comment]
> I tried tinycore and it doesn't work

Tiny Core Linux is my main distro and I run AppImages on it on a daily basis. I'm actually using a homebrewed AppImage of brave-browser right now to create this post.

Tiny Core is very barebones out of the box, on purpose. These commands should add what you need in order to run most AppImages:

```
$ tce-load -wi fuse bash
$ sudo ln -s /lib /lib64
$ sudo ln -s /usr/local/etc/fonts /etc/fonts
```
If after the above you have issues with a particular AppImage, just ask for help at http://forum.tinycorelinux.net (send me a personal message there to let me know about your post, as I don't check the forum on a regular basis).

**Comment by bdantas** [comment]
@vinniec 
This one may be due to AppRun making a wrong assumption about interpreter available on TCL:
`name.AppImage: line 1: syntax error: unexpected "("`
Please post output of these commands:
```
$ ./name.AppImage --appimage-extract
$ head ./squashfs-root/AppRun
```
This one sounds like an architecture mismatch between the AppImage and the OS (TCL in this case):
`bash: ./name.Appimage: cannot execute binary file: Exec format error` 
Please post output of:
```
$ file name.AppImage
$ uname -m
```

**Comment by vinniec** [comment]
then, I go a little slow because every time I have to reboot the pc and start tinycore, but then to answer on github or I write from the phone or I have to reboot, maybe I try to install a browser on tinycore.
This is to say that if you have available also some other contact for me is ok (matrix / telegram).
I'll reboot now and try what you said.

**Comment by vinniec** [comment]
Not possible to etract:
```
tc@box:/mnt/sdc2/download/line$ ./Linedancer-e6ea833-x86_64.AppImage  --appimage-extract
./Linedancer-e6ea833-x86_64.AppImage: line 1: ©: not found
./Linedancer-e6ea833-x86_64.AppImage: line 2: }¦P7pysH¼°_f¸§h: not found
^[[?1;2c./Linedancer-e6ea833-x86_64.AppImage: line 1: ©bÀ@@: not found
./Linedancer-e6ea833-x86_64.AppImage: line 1: ELFAI: not found
./Linedancer-e6ea833-x86_64.AppImage: line 19: syntax error: unterminated quoted string
```

file
```
file name.AppImage
tc@box:/mnt/sdc2/download/line$ file Linedancer-e6ea833-x86_64.AppImage 
Linedancer-e6ea833-x86_64.AppImage: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, stripped
```

uname
tc@box:/mnt/sdc2/download/line$ uname -m
i686

**Comment by bdantas** [comment]
> tc@box:/mnt/sdc2/download/line$ file Linedancer-e6ea833-**x86_64**.AppImage 
> Linedancer-e6ea833-x86_64.AppImage: ELF **64-bit** LSB executable, **x86-64**, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, stripped
>
> uname
> tc@box:/mnt/sdc2/download/line$ uname -m
> **i686**
There's your problem. The AppImage is 64-bit but you are running TCL 32-bit. You need the 64-bit version of TCL (the TCL developers call it "x86 Pure 64"). Get it then do the steps in my first post above and you should be good to go.

**Comment by vinniec** [comment]
Ok, I didn't think that by base tinycore was 32bit!
Anyway now they don't give that error anymore, they still don't seem to start but I think it's because I'm missing the started graphics server.
These are the errors I got after installing all the libraries that appimages reported me missing:

```tc@box:/mnt/sdd2/download$ cd ./line/
tc@box:/mnt/sdd2/download/line$ ./Linedancer-e6ea833-x86_64.AppImage 
Failed to create display

tc@box:/mnt/sdd2/download$ ./VSCodium-1.51.1-1605141118.glibc2.16-x86_64.AppImag
e 
Xlib:  extension "XInputExtension" missing on display ":0.0".
Xlib:  extension "XInputExtension" missing on display ":0.0".
Xlib:  extension "XInputExtension" missing on display ":0.0".
Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.
Xlib:  extension "XInputExtension" missing on display ":0.0".
Xlib:  extension "XInputExtension" missing on display ":0.0".
```

I think I need to create a tinycore usb with the graphics server installed and boot that, do you recommend xorg/wayland?

**Comment by bdantas** [comment]
If the AppImages you are running are GUI applications, you need a graphics server (Xorg is better tested on TCL than Wayland). I would also recommend adding some kind of window manager. 
  
For window manager I like fluxbox, so I'd do `tce-load -wi Xorg-7.7 fluxbox` (feel free to replace fluxbox with your favorite WM, of course) then reboot. After the reboot, Xorg and the WM will start automatically with their default settings and you can re-test the AppImages to see if they are satisfied or if they need something more.
  
You can create a USB (or small hard drive partition) with `/boot`, `/opt`, and `/tce` directories but now we are off-topic because this is specific to TCL and not directly related to AppImageKit. Take a look at the first few chapters in this book: http://www.tinycorelinux.net/corebook.pdf (the book is a few years old but TCL is one of the most conservative distros that exist, so virtually everything in the book is still applicable).
  
If you need TCL-specific help, ask in the forum or send me an email. You can reach me at gnuser AT dantas dot airpost dot net.
  
Happy hacking!

**Comment by vinniec** [comment]
Ok, after several tests I managed to install tinycore on a usb so I can edit it (before I started it from [Ventoy](https://www.ventoy.net), but this is actually offtopic so I think I'll write you an email.
But I wanted to relaunch this issue @probonopd taking advantage that this issue is already closed.
Why don't you create an official distro to run AppImages? at the end creating a redistribution of tinycore shouldn't be very difficult (ventoy did it too) and maybe you could use it as a reference distro to create new Appimages (starting from a distribution so basic you have to pay more attention to dependencies than normal).
