### ISSUE TITLE
Consider setting XDG_DATA_DIRS in runtime.c

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#1154]
Setting `XDG_DATA_DIRS` in `runtime.c` _if_ `<AppDir>/usr/share` exists would allow e.g., applictions deployed with linuxdeployqt to "just work" without the need for an AppRun script (just a symlink).

Currently we are doing it only in `apprun.c` which AppImages made with `linuxdeployqt` is not using.

https://github.com/AppImage/AppImageKit/blob/8bbf694455d00f48d835f56afaa1dabcd9178ba6/src/AppRun.c#L180-L181

Any objections?

**Comment by bphd** [comment]
And how to set it punctually without extracting?

**Comment by bphd** [comment]
In that case an environment variable seems to be set into AppImageKit to be applied on all softwares run with it. But what if we want to apply at run an arbitrary variable, rather than globally on all softwares?

Like for example applying defaultTool=pen to inkscape.appimage

**Comment by probonopd** [comment]
```
export defaultTool=pen
./Inkscape-*.AppImage
```

The variable will not be exported to all your running software, but only to what you launch from this terminal window.

**Comment by bphd** [comment]
Did that, don't work

**Comment by izzylaif** [comment]
What I do for furryfox is to launch it through .desktop file, with this launch command:
`Exec=/home/LOCATION/firefox.sh %u`
which launches .sh script to call furryfox with the following inside
`#!/bin/bash
export MOZ_ENABLE_WAYLAND=1
/mnt/LOCATION/firefox.AppImage $1`

which does launch ff in wayland mode.

However, this is really weird that we have to jump through hoops.

I understand that @probonopd is p1ssed off with the community for all the valid reasons, but here we are, AppImage enjoyers that will be with you to the end. Especially given other package formats suck and are just a distribution way, not really a portable solution with .home and .config.

Maybe @probonopd reconsider his decision to rely on the appimage packagers?

**Comment by bphd** [comment]
> with the following inside
> `#!/bin/bash export MOZ_ENABLE_WAYLAND=1 /mnt/LOCATION/firefox.AppImage $1`

Maybe GitHub formatting is wrong, but are you sure that is supposed to work as is? Normally it's two different commands, you aren't supposed to export and execute on the same line, at least on my part that doesn't work



> launch it through .desktop file

That's actual hoops. Going desktop > script > export + execute result to the same as just export and execute in one terminal, which don't work for me as stated up there. And I can't figure out why. The AppRun don't touch the variable that I try to fiddle with. I could extract and tweak, but I want to be able to run the AppImage in itself



> AppImage enjoyers that will be with you to the end

I personally don't like the AppImage concept. I prefer from far distribution specific package manager. Universal executable was a Windows flaw that was resolved on Linux, it's such a heresy to have library per binary rather than keeping them in a central place for binaries to use them. It's just that the package manager of my distribution is utterly complicated and there aren't yet package for the software I want, so I fiddle with the AppImage meanwhile

Thing is that I can't run it as is because fuse fail to execute fusermount because permission issues. It seems that fusermount is somewhat considered a root binary but I need to execute the software as simple user, using root would cause many problems. I don't know how to use fusermount as non root without fiddling with system files permisisons. So anyway I used --appimage-extract-and-run and it works as it doesn't need anymore fusermount, but in that configuration it doesn't seem to read environment variables. And I try to avoid to manually launching extracted AppImage to stay in the AppImage workflow, and not just using a portable binary

**Comment by probonopd** [comment]
It sounds like you're having issues with FUSE (Filesystem in Userspace) and the `fusermount` binary. If `fusermount` is not working, it's likely due to permission issues. To fix this, you can try adjusting the permissions on the `fusermount` binary.

You can use the following command to check the current permissions:
```bash
ls -l /usr/bin/fusermount
```
If the permissions are not correct, you can use the following command to adjust them:
```bash
sudo chmod 4755 /usr/bin/fusermount
```
This will set the permissions to allow non-root users to execute fusermount with root privileges.

If you're still having issues, you may want to check the FUSE documentation or seek further assistance to troubleshoot the problem.

**Comment by probonopd** [comment]
> I personally don't like the AppImage concept. I prefer from far distribution specific package manager. 

Then just use those. The the AppImage concept is here so that the same binaries can be used no matter which distribution someone is running.

**Comment by izzylaif** [comment]
> I prefer from far distribution specific package manager.
that is until you are deemed a terror1st by the "international" community, and Mr. Torvalds shows you the finger, and disables downloading based on your IP/race/color/political affiliation.
No thank you, please give me direct software downloads, manual installation and .ini files in the folders without spreading the app files across the entire filesystem. Basically like in the olden DOS days. I'm not relying on a centralized distribution.

As per your problem, please see attached. Do not forget to change the /LOCATION/ paths and mark .sh as executable.
[firefox.zip](https://github.com/user-attachments/files/17687076/firefox.zip)

**Comment by probonopd** [comment]
I don't use Wayland, it just [breaks](https://gist.github.com/probonopd/9feb7c20257af5dd915e3a9f2d1f2277) too many things.

**Comment by bphd** [comment]
>> try adjusting the permissions on the `fusermount` binary

> I don't know how to use fusermount as non root without fiddling with system files permisisons

`-r-sr-xr-x 1 65534 overflow 35408 Nov  5 11:04 /run/setuid-programs/fusermount3`

`-r-sr-xr-x 1 65534 overflow 56576 Nov  5 11:04 /run/setuid-programs/mount`

Fiddling permissions of the file would be useless as it will be reset by my distribution. Rather AppImage should ask the right way to use the software

But I don't really think the problem is about accessing the binaries, but rather that when using mount, you need specific Linux permissions to use the right to mount on an OS, and permissions to all the paths you ask to mount from/to. I think that it's that that is denied. Because as a simple user I can execute such binaries

**Comment by bphd** [comment]
>> Then just use those

> It's just that the package manager of my distribution is utterly complicated and there aren't yet package for the software I want, so I fiddle with the AppImage meanwhile

**Comment by bphd** [comment]
> you are deemed a terror1st

You can just set up a new repository. It's the same problem being forbidden to downloading from provider or from distribution repositories. In both cases maintainer of those don't want you to access. So you setup a new repository of binary sources and a new repository of distribution specific scripts/packages. You really shouldn't care about what a country community think about you. They don't want to work with you, it's their right, from here and now, you work and go forward without them, they don't deserve you if they don't want you. No need to be so bitter about their behavior really, it just shows flaws

**Comment by bphd** [comment]
>> I'm not sure why you insist on --appimage-extract-and-run

A new time, reading my problem would have been useful to actually try to help me

> Thing is that I can't run it as is because fuse fail to execute fusermount because permission issues. It seems that fusermount is somewhat considered a root binary but I need to execute the software as simple user, using root would cause many problems. I don't know how to use fusermount as non root without fiddling with system files permisisons.

**Comment by izzylaif** [comment]
It's a full package, with .desktop and icon

**Comment by bphd** [comment]
>> you don't need it to pass the wayland variable

But I need it for the app... to run?

> and it works as it doesn't need anymore fusermount, but in that configuration it doesn't seem to read environment variables

**Comment by bphd** [comment]
> I don't use Wayland, it just [breaks](https://gist.github.com/probonopd/9feb7c20257af5dd915e3a9f2d1f2277) too many things.

Sure, it's your right. On my part it breaks way less things that it give new functionalities. It wasn't all the time the case. Before in early WayLand and with my nViDia hardware, it used to crash my whole system and a lot of other casualties

But anyway, I'm not here to ask for WayLand support. Just to inherit environment variable

**Comment by izzylaif** [comment]
> But I need it for the app... to run?

ok, can you run it that way
Unpack:
./*.AppImage --appimage-extract
Go to the folder
cd squashfs-root/

The above needs only to be done once

execute the unpacked:
./AppRun

**Comment by bphd** [comment]
> It's a full package, with .desktop and icon

I don't need the icon, I use another one. I don't need the desktop, it just invoke a script that export a value that I already export in my shell myself. What I need is support as to why the appimage don't read such exported variables

**Comment by probonopd** [comment]
Which operating system and version are you on @bphd?

**Comment by probonopd** [comment]
AppImage is designed for and tested on _mainstream_ distributions like Ubuntu, Debian, Mint, etc.
Also most application developers will probably never have tested their AppImages on Guix.
Possibly Guix is just too different from _mainstream_ distributions like Ubuntu, Debian, Mint, etc.?

**Comment by bphd** [comment]
> Guix is just too different

It indeed does have many differences, but I try to even out those to make it work, for example, some:

To be able to execute an app image you need to emulate FHS, and that requires a container. That container needs to have access to some paths and libraries for the appimage. That article give the command to give such access https://guix.gnu.org/en/blog/2023/the-filesystem-hierarchy-standard-comes-to-guix-containers/

You need to give `fuse` for fusermount3 and `util-linux` for mount. Variable in itself seems to be inherited without the need to `--preserve` those. But I can't figure out exactly how AppImage intend to mount things with fuse without any root rights. I am in the fuse group, that is supposed to set all needed permissions right, I guess?

**Comment by probonopd** [comment]
Many AppImages need `fusermount` (from libfuse2) rather than `fusermount3` (from libfuse3).

**Comment by bphd** [comment]
Idk if it's fuse or fusermount3 or the AppImage itself, but one of the three seeks for /usr/bin/fusermount3 and there is nothing over there. Guix repositories have packages that are compiled to not use /usr/bin path but rather /run/setuid-programs and Guix does provides fuse/fusermount3, that should be configured right. So I suspect that it's the AppImage that seeks under /usr/bin, but it's illogical for the AppImage itself to do anything else than asking to be mounted simply. So I don't understand

**Comment by bphd** [comment]
Guix tries to modify compilation process of fuse to use its own paths

```scheme
(substitute* "lib/meson.build"
  (("-DFUSERMOUNT_DIR=[[:graph:]]+")
   "-DFUSERMOUNT_DIR=\\\"/var/empty\\\""))
```

Thing is that it don't seem to have any effect, still tries to search under /usr/bin

**Comment by probonopd** [comment]
Then you need to put it there, e.g., by symlinking fusermount3 there.

This is the biggest problem of "Linux": That there is more than 1 distribution, and they don't even agree on where to put things. Drove me to FreeBSD.

**Comment by bphd** [comment]
Personally it drove me nuts instead to FreeBSD

The workaround worked back in... 2014 (😅) https://git.savannah.gnu.org/cgit/guix.git/commit/gnu/packages/linux.scm?id=bd6639026bc04c9461545d199253ca64e1cb3467 (with a modification that shouldn't change anything in 2021 though https://git.savannah.gnu.org/cgit/guix.git/commit/gnu/packages/linux.scm?id=4f4477a77e699142ea30162fd96519579ec9e12b)

But probably fuse has totally changed in a decade and now the paths aren't replaced and it seeks in default developers intented paths that aren't right

I could workaround by putting things in /usr/bin, but that won't repair the problem at Guix level, and even then, maybe it won't work, like idk, it wouldn't like a symbolic link or that path it not touchable in Guix, idk

**Comment by bphd** [comment]
A veeeeeeeeeeeery convoluted way could be to create an overlay filesystem that will make available both the contents of /usr/bin and /run/setuid-programs under /usr/bin, but only for the AppImage under `unshare`. That doesn't resolve the problem, but it's a convoluted workaround, like I said

```shell
# Step 1: Create directories for the overlay layers and work
mkdir -p /tmp/overlay/{upper,work,merged}

# Step 2: Use `unshare` to enter a new mount namespace and overlay /usr/bin
LANG=US sudo unshare --mount -- bash -c '
  # Bind mount /usr to itself to make it writable within the namespace
  mount --bind /usr /usr
  mount --make-private /usr

  # Mount overlayfs at /usr/bin with both /usr/bin and /run/setuid-programs as lower layers
  mount -t overlay overlay -o lowerdir=/usr/bin:/run/setuid-programs,upperdir=/tmp/overlay/upper,workdir=/tmp/overlay/work /usr/bin

  # Check the overlay at /usr/bin to verify the merged view
  printf "%s\n" "Inside overlay at /usr/bin (should see files from both /usr/bin and /run/setuid-programs):"
  LANG=US ls -l /usr/bin

  # Run your specific command here that requires the merged /usr/bin view
  # For example: application.AppImage

  read -p "Press Enter to exit and discard the overlay..." # To give time observing outside the overlay/unshare
'

# Cleanup after unshare exits
rm -rf /tmp/overlay
```

**Comment by bphd** [comment]
Trying `guix shell --container --emulate-fhs --share=/dev/fd/$number -- <(sed 's/\/usr\/bin/\/run\/setuid-programs/g' ZenBrowser.AppImage)` don't give that much better results

Because AppImage/distribution default behaviour seem to mount to /tmp/$distribution.$random/$thingToMount. Thing is that when $thingToMount begin from root, it gives a double slash (`//`) and Linux is no-no with that. And I don't know how to lint that slash correctly. I tried to create the modified binary first and then execute it outside FHS it gives a segfault, and inside it does nothing, only `--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV +++`
