### ISSUE TITLE
AppImages crash due to library incompatibilities 

### ISSUE THREAD

**Issue by NobodyIII** [AppImage/AppImageKit#1198]
With my current system, Kubuntu 22.04, using AppImages' bundled libraries does more harm than good. 2 out of the 3 AppImages that I use frequently, FreeCAD and Cura, crash on startup. I can fix this by using LD_PRELOAD to force the AppImages to use system libraries, but unless I do that, they fail on startup due to the bundled libraries being unable to support the system libraries. Here, AppImages create dependency problems, while their primary purpose, from my understanding, is to solve them.

As to the solution, I'd be inclined to get rid of AppImages entirely, and simply use system libraries, with some sort of hybrid package manager that can use system libraries, with the option of using newer or obsolete ones when required.

But I'm not aware of such a system existing, unfortunately, and I don't expect everyone to abandon this project. However, you can probably mitigate this problem by making AppImages prefer the newer of the system library and the bundled one.

Here's an example of the error output:
`libGL error: MESA-LOADER: failed to open radeonsi: /tmp/.mount_FreeCAC7MJN8/usr/bin/../lib/libstdc++.so.6: version 'GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libLLVM-13.so.1) (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi: /tmp/.mount_FreeCAC7MJN8/usr/bin/../lib/libstdc++.so.6: version 'GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libLLVM-13.so.1) (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /tmp/.mount_FreeCAC7MJN8/usr/bin/../lib/libstdc++.so.6: version 'GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libLLVM-13.so.1) (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast`

**Comment by probonopd** [comment]
Hello @NobodyIII. Please do report those issues to [FreeCAD](https://github.com/FreeCAD/FreeCAD/issues) and [Cura](https://github.com/Ultimaker/Cura/issues/11856), respectively. These issues are concerning what is _inside_ those particular AppImages, not regarding the AppImage file format and runtime itself. At least in the case of Cura, there are workarounds and a solution posted in the respective thread.

Thanks for sharing!

Reference:
* https://github.com/Ultimaker/Cura/issues/11856

**Comment by benlovage** [comment]
So each AppImage maintainer has the responsibility to ensure that their library versions are always new enough to support any system libraries that they're using? Or should they be using system libraries whenever possible?

**Comment by probonopd** [comment]
It's complicated! Mainly because the "Linux desktop userland" is an uncoordinated mess that makes little to no guarantees. Whole books could be filled about this subject. But two strategies are promising:

1. Build your application on the oldest still-supported LTS Linux distribution release. This way, you can be sure that most of your users will have this version or a newer version of the core system libraries. Bundle all libraries except those core system libraries that can reasonably expected to be shipped by default by all distributions (e.g., glibc).
2. Bundle _all_ libraries (down to, and including, glibc). This way you don't have to build on an older system but the bundle will be larger.

Note that these tradeoffs are not AppImage specific, but are inherent to how "Desktop Linux" is using shared libraries.
