### ISSUE TITLE
fusermount: too many FUSE filesystems mounted error

### ISSUE THREAD

**Issue by krillin666** [AppImage/AppImageKit#1211]
The following error has been preventing me from launching any AppImage file I have:
```
fusermount: too many FUSE filesystems mounted; mount_max=N can be set in /etc/fuse.conf

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
```
I'm running Fedora 36. The only other relevant information I can give is that until 2 days ago I was using Xorg and now switched to Wayland.

Thank you for your time !

**Comment by probonopd** [comment]
When this happens, what is the output of `mount`, do you see many fuse mounted mountpoints there?

**Comment by BobSynfig** [comment]
> fusermount: too many FUSE filesystems mounted; mount_max=N can be set in /etc/fuse.conf
And applying this advice isn't working?

**Comment by probonopd** [comment]
@BobSynfig when this happens, what is the output of `mount`, do you see many fuse mounted mountpoints there?

**Comment by BobSynfig** [comment]
I doubt that AppimageKit is responsible of this.
I am not affected myself (Ubuntu 20.04), the limit by default is 1000, which should be sufficient.
With some snaps mounted, I have 142 entries (`mount|wc -l`)
But is some cases, it seems that unionfs, onedrive or some other cloud system could induce high number of mount points.
mount without umount from a script? In a cron task?
See https://forum.vyos.io/t/large-numbers-of-unionfs-fuse-mountpoints/1032  
and https://lei.im/too-many-fuse-filesystems-mounted/
@krillin666: It would be useful not only to count but also to list the duplicates in mount to find the origin of the issue

**Comment by probonopd** [comment]
I'd like to find out what causes so many FUSE mounts to be there.

**Comment by BobSynfig** [comment]
I think this is connected to Flatpak, @krillin666 didn't mention this https://github.com/flatpak/flatpak/issues/4051
There are some (known) bugs in Flatpak leading to this: https://github.com/flatpak/flatpak/issues/5104
Also here https://ask.fedoraproject.org/t/flatpak-installation-and-update-errors/15245
Is the user member of fuse group?
Is it because of mix of install of Flatpak with sudo and unpriviledged user?
Some more info about revokefs could be found here https://www.altlinux.org/Flatpak and here https://www.altlinux.org/Control (use Google Translate, I don't understand russian either)

Once again, _AppImageKit is not the root cause of this_, just a "victim" of the lack of available mountpoints in the system _in Fedora because of Flatpak_!

P.S.: Try to change sockets authorizations for Flatpak's sockets with Flatseal, there are options for X11 and Wayland.

**Comment by hyuri** [comment]
Same issue here.

@probonopd 
> When this happens, what is the output of `mount`, do you see many fuse mounted mountpoints there?

My output of 'mount' is 1035 lines. The last 1000 lines are:

`appimagelauncher-lite.AppImage on /tmp/.mount_appimayJ2D6d type fuse.appimagelauncher-lite.AppImage (ro,nosuid,nodev,relatime,user_id=1000,group_id=1000)`

**Comment by hyuri** [comment]
A temporary alleviation for those affected like me:

I managed to temporarily alleviate the problem by unmounting all the appimagelite fuses running this:
`mount -l | grep ".mount_appima" | awk -F " " '{print "fusermount -u " $3}' | bash`

But I noticed that AppImageLite continues mounting multiple fuses, so I'll probably have to run this again in a few hours.

**Comment by probonopd** [comment]
Please let us know if you think we can change anything on our side. Thanks!
