### ISSUE TITLE
fallback to appimage-extract-and-run when libfuse isn't found

### ISSUE THREAD

**Issue by sim1cent** [AppImage/AppImageKit#1213]
I think this would mitigate the problem with those distributions which don't ship with libfuse2.
It would be slower and more expensive on memory though.

**Comment by v3ss0n** [comment]
This bug is breaking AppImage usability on  fresh ubuntu. It is killing AppImage , this need to be addressed immediately if this format to be useful in future. I am willing to help if there are contributor still remaining. If no maintainers remains active , I would like to request transfer of maintainer-ship to community.

**Comment by probonopd** [comment]
Well... Ubuntu decided not to ship it from one release to the next, without any grace period during which both libfuse2 and 3 were shipped by default.

So, to enable the Universe repository and install `libfuse2` on Ubuntu:

```
sudo add-apt-repository universe
sudo apt-get update
sudo apt-get install -y libfuse2
```

**Comment by v3ss0n** [comment]
```
sudo add-apt-repository universe
sudo apt-get update
sudo apt-get install -y libfuse2
```

I can't tell that to end users .
