### ISSUE TITLE
Fuse nearly broke my Kubuntu 23.04 install, had to satisfy ntfs-3g package to fix

### ISSUE THREAD

**Issue by GhostCoder22** [AppImage/AppImageKit#1284]
So just the other day, I found an Fedora-only Android emulator built as an AppImage executable and so during my Google search found FUSE to run the said AppImage executable and so installed it on my Linux distro of choice, which is Kubuntu 23.04. Even though I followed FUSE's installation to the letter, there was problems that rose immediately. Not only did the AppImage executable refuse to run with FUSE, but FUSE actually very nearly broke my Kubuntu installation.

As part of FUSE's installation, several packages was removed (some of which like **ntfs-3g** is required). Both **Flatpak** and **Snap** backends was also removed and god knows what else since I didn't take a screenshot of what was removed. After FUSE's removal in Discover, I had to re-add both **Flatpak** and **Snap** backends and just recently fix the NTFS-3g driver with the command **sudo apt satisfy ntfs-3g** just so I could continue mounting all my NTFS-formatted drive partitions I originally made with Windows. _None of this should have never happened during the install of any package._

If I had some sense, I would have taken a screenshot of all the packages FUSE removed during it's install as proof of what it was doing. Please fix this so no one else need not go through what I just have gone through!

**Comment by probonopd** [comment]
This is a bug in your Linux distriution then, which needs to be fixed there. The proper command to install libfuse2 is `sudo apt install libfuse2`; and you should not proceed if it wants to uninstall anything. (Things like this are the reason I designed AppImage in a way that you don't need package managers.)

For AppImage, we are removing the requirement to install libfuse2; the new https://github.com/AppImage/type2-runtime/ is doing away with it so that AppImages using it will no longer need libfuse2.
