### ISSUE TITLE
Make AppImages [optionally] self-updatable

### ISSUE THREAD

**Issue by lbssousa** [AppImage/AppImageKit#133]
Current AppImages can be updated via an external tool, AppImageUpdate. I wonder if AppImageUpdate's heuristic could be embedded in the AppImage itself. For example, a given AppImage's AppRun could check for updates, and ask user to download them if available, before spawning the application itself.

**Comment by RazZziel** [comment]
Not before spawning the application itself: what I want when I click on an application is to start using it right away, not to wait for it to connect to the server, check for updates, timeout if I'm offline or if my connection is spotty, etc.

For instance, it's silly but one very good design decision of Chrome over Firefox is that is updates in background, instead of delaying the whole UX looking for updates.

Nonetheless, it's probably a good idea, and it could work well if background update is implemented, more or less like what I commented in https://github.com/probonopd/AppImageKit/issues/67#issuecomment-170328997 for desktop integration.

**Comment by probonopd** [comment]
Someone packaging an app as an AppImage could put `appimageupdate` and its dependencies into the AppImage, and whenever the user asks the payload app to update itself, the app could run `appimageupdate` to update the AppImage itself (`appimageupdate $APPIMAGE`). I don't see why it wouldn't work; as AppImageUpdate can be used to update itself already today.

**Comment by shoogle** [comment]
Perhaps updating (and other AppImage-specific functions) could be done via a standardized set of command line options:
```bash
./Program.AppImage # launches Program
./Program.AppImage --install # performs desktop integration
./Program.AppImage --remove # removes file created for desktop integration
./Program.AppImage --update # updates the AppImage
```
Now an "AppImageManager" program can just call the relevant option for the AppImage. AppImageKit could provide example scripts for "--install", "--remove" and "--update".

This is basically what I've done for MuseScore where [AppRun](https://github.com/musescore/MuseScore/blob/master/build/Linux%2BBSD/portable/AppRun.in) launches [bin/portable-utils](https://github.com/musescore/MuseScore/blob/master/build/Linux%2BBSD/portable/portable-utils.in) - a bash script that's only 11.5 kB in size.

**Comment by RazZziel** [comment]
Tried that, and it turned out horrible :P because:
* Arguments like `--install`, `--remove`, etc, may easily collide with arguments that belong to the application inside the AppImage (we have that problem with the `--icon` argument, applications that use a `--icon` argument can't be packaged as AppImages)
* There's already a bunch of AppImages out there without those arguments, and there's no way to enforce those arguments on all future AppImages (anyone can change the runtime), so if `AppImageManager` tries to use those arguments in order to handle desktop integration on all the AppImages in a directory, chances are that many of those AppImages will actually run at the same time, bringing the PC to its knees (happened to me with [AppImageMonitor](https://github.com/probonopd/AppImageKit/tree/master/AppImageMonitor.AppDir) and a whole bunch of AppImages from http://www.portablelinuxgames.org/, before deciding to move away from `--icon`)

If there's an `AppImageManager` program (à la [AppImageMonitor](https://github.com/probonopd/AppImageKit/tree/master/AppImageMonitor.AppDir)) then it can easily implement all desktop integration itself, and if each AppImage includes desktop integration inside (à la [desktopintegration](https://github.com/probonopd/AppImageKit/blob/master/desktopintegration)), it should be handled more or less automatically, because most users won't mess with the shell; I think desktopintegration does it pretty well right now.

**Comment by shoogle** [comment]
You could use `---install`, etc. to avoid collisions. The advantage is that the features can be used standalone (without any AppImageManager program). AppImageKit could check for those arguments and warn or maybe even refuse to package if they don't exist.

**Comment by probonopd** [comment]
@shoogle would you be willing to consider making [portable-utils.in](https://github.com/musescore/MuseScore/blob/master/build/Linux%2BBSD/portable/portable-utils.in) so generic as to it being possible to use for all AppImages? I had started on working something similar here: https://github.com/probonopd/AppImageKit/issues/84 maybe we can take the best of both and make one that really rocks?

**Comment by shoogle** [comment]
@probonopd, sure, but no time right now, unfortunately. Maybe in a few weeks time.

But I'm not sure if you understood me about the command line options? They would be there for the user, not for an external daemon. (In fact they would be there to make it possible for the user to update and install without a daemon, though they would also make the task of creating a daemon much easier!)

**Comment by probonopd** [comment]
Yes I agree @shoogle (the daemon comment was more in response to @RazZziel)

**Comment by RazZziel** [comment]
My point is, there's a good use case for embedded desktop integration and a good use case for daemonized desktop integration, but I think they should not mix.

Having code from inside an AppImage running by surprise just by downloading a file just sounds dangerous, IMHO it's a vector for malicious AppImages to run any code they want in the user's machine, without the user knowing what happened (the user didn't even click on the AppImage). It could turn Linux into Windows 98 really quick, unless there's some mechanism to only let signed AppImages to run (AppImages signing should probably happen to some extent).

Command options for the shell could be fine (as long as there's no possible collision), although I don't think it's good for the AppImage UX to need the user to be comfortable around the shell, that's why I like [desktopintegration](https://github.com/probonopd/AppImageKit/blob/master/desktopintegration)'s semi-automatic approach better, maybe with the improvements of running it in the background (https://github.com/probonopd/AppImageKit/issues/69#issuecomment-170400011, easy to implement, faster, unintrusive), or maybe even an implicit daemon embedded in the AppImage itself (https://github.com/probonopd/AppImageKit/issues/69#issuecomment-170712801,  https://github.com/probonopd/AppImageKit/issues/67#issuecomment-170328997, a bit more involved and a bit intrusive, but as long as it's optional so only users that want it can opt-in I think it could be good).

**Comment by probonopd** [comment]
I think we should ask the user in a GUI whether desktop integration should be installed, as long as a) no daemon is running and/or b) as long as the user has not opted out (e.g., by creating a certain file or setting a certain environment variable). 

Also, I think that a daemon can have its merits, but it should a) be purely optional and b) be installed by the distribution or by the user (preferably packaged in native distribution format since it is a piece of infrastructure), but not by random AppImages. Otherwise I can see multiple different AppImages wanting to run multiple different daemons, which is clearly not a good idea.

Opinions?

**Comment by lbssousa** [comment]
> You could use ---install, etc. to avoid collisions (or even --AppImage install).

I'd prefer something like

```
Foo.AppImage --appimage-intrinsic-options -- --application-options-not-handled-by-appimage
```

Maybe the most simple thing to do in this way is showing a desktop notification whenever an AppImage update is available.

**Comment by shoogle** [comment]
A usable GUI interface (e.g. notifications) is certainly desirable, but I think they should be useable from the command line too.
<pre>
Foo.AppImage --AppImage install
</pre>
is much easier to remember and use than
<pre>
Foo.AppImage --appimage-intrinsic-options install
</pre>
In any case, I'm not sure that "intrinsic" is the right word here. It might give the impression that this is an option that is "intrinsic" to this particular AppImage, rather than "intrinsic" to all AppImages.

**Comment by shivarajnaidu** [comment]
How about `appimage -i packagename` it's like `dpkg -i` simple to use.. Please ensure simplicity of commands ..friends.. It's important .

**Comment by probonopd** [comment]
Why not `./Some.Appimage --update-appimage` or something like this? But in the end it is up to the application in question. AppImage is just a container that holds the software inside, and that software can implement updates however it likes.

**Comment by shoogle** [comment]
@shivarajnaidu I think you might have got the wrong idea. AppImages are supposed to make package managers obsolete, they are not supposed to be a new type of package manager. This is a command that would be given to a *single* AppImage to install or update *just that one AppImage*.

@probonopd but the advantage of standardisation is that it:

1. makes things easier for the user (no new commands to learn!)
2. makes things easier for the programmer (no decisions to make!)
3. allows us (or anybody else) to build an AppImage daemon/package manager that could update all AppImages at once by simply calling the standard option for each one.

Standardising the install and update commands actually gives the developer greater flexibility because they can control what the command actually does, yet they can still be sure that users will be able to find it and that it will work with a generic daemon/package manger.

**Comment by probonopd** [comment]
@shoogle for the standardization, it is mandatory that each AppImage has the [update information](https://github.com/probonopd/AppImageKit/blob/master/AppImageUpdate.AppDir/README.md) (kind of a repo without the repo) embedded in a standard location, so that an updater app can update all the AppImages. It is not necessary for each AppImage to standardize on CLI arguments; although there might evolve some best practice.

**Comment by shoogle** [comment]
I know it's not mandatory at the moment, but I think it should be. My preference would be:

```bash
./Foo.AppImage --AppImage options   # Prints a list of AppImage intrinsic commands
./Foo.AppImage --AppImage install   # Performs desktop integration
./Foo.AppImage --AppImage update    # Updates the AppImage
./Foo.AppImage --AppImage remove    # Removes desktop integration
./Foo.AppImage --AppImage version   # Prints the version of AppImageKit used for packaging
```

This would allow someone to write an extension for GNOME/Nautilus where you could right-click on an AppImage and be presented with a list of options, like this:
![appimage-context-menu](https://cloud.githubusercontent.com/assets/11011881/15298664/58e527e0-1b98-11e6-98b0-8df95d30252c.png)

The list of options would be populated automatically by calling `Foo.AppImage --AppImage options`.

**Comment by probonopd** [comment]
How could we make these hooks as transparent to the person packaging an app as possible? And how can we find out if a particular AppImage supports calling `Foo.AppImage --AppImage options`?

**Comment by shoogle** [comment]
We would provide default scripts for each option that the packager could use or replace with their own if they prefer. We would check for support of ` - - AppImage options` by calling it, checking for errors and seeing if the output is the correct format. If it is not supported then no context menu would be displayed.

**Comment by shoogle** [comment]
I've done a little research. It seems Nautilus extensions can be written in C or in Python. Python extensions (and possible C extensions, I can't tell) can be installed for all users or just for a single user by putting the .py file in ~/.local/share/nautilus-python/extensions. So you could ship this extension in its own AppImage, or even add the .py script to all AppImages!

**Comment by shivarajnaidu** [comment]
:+1: @shoogle
:+1:  @probonopd 
good idea ,default scripts are simple and best thing for app image . 
Appimage gives awesome portability to linux apps.. at the same time centralized package management feature also important. and it's one of the main features of Linux systems. so it should be there.. at least for convenience. and
 @probonopd  **I heard a term called alpha level updates** ... means **downloading only changed part of binaries** instead of downloading whole package from online. I think , providing this as optional feature will make appimages  more awesome. so please consider this too.

**Comment by probonopd** [comment]
See AppImageUpdate "Delta" updates...

**Comment by shoogle** [comment]
On second thoughts is probably not a good idea to populate the right click lift by using a command line option like `--AppImage options` because it would result in unknown code being executed simply by the user right-clicking. A better way to populate the list would be to embed it in the ISO 9660 Volume Descriptor.

**Comment by shivarajnaidu** [comment]
@probonopd 
is that app image already offering **Delta updates** ?

**Comment by shoogle** [comment]
@shivarajnaidu Yes, all AppImages can be updated via delta updates already, providing the author generates a [zsync](http://zsync.moria.org.uk/) file. AppImageUpdate is a tool for updating other AppImages. It uses the zync files to perform delta updates (only fetch the bits of the file that have changed). All of @probonopd's AppImages [have zync files](https://bintray.com/probono/AppImages/Audacity/view#files) - they are generated automatically by [bintray.sh](https://github.com/probonopd/AppImages/blob/master/bintray.sh).

**Comment by abnerlee** [comment]
+1

**Comment by gameslayer** [comment]
why don't they just provide the app image in the ppa's himself to not further course more issues trying to having more systems running just to update it on top of they systems package manager or something simular to snap package updater at least

**Comment by shoogle** [comment]
The point is all systems have different package managers and the developer was using AppImages specifically to avoid learning all them.

Also, AppImages wouldn't work in PPAs anyway due launchpad's requirement for uploading source (rather than binary) packages and the limitations of the Debian packaging system (which can't add files to the user's home directory and also requires `sudo`).

**Comment by gameslayer** [comment]
Well than we will have to work on it's own appimage manager that updates them all instead of having the software update itself which is worse running software running it's own updaters in the background

**Comment by probonopd** [comment]
It is part of the AppImage philosophy that the user can interact with AppImages directly without the need of a manager. For example, the user can decide
* Where to store AppImages (e.g., on the internal hard disk, an external hard disk, a USB stick, a CD-ROM, a network drive, etc.) - something package managers normally don't do
* Whether to delete the old version after updating to the new version or not - something package managers normally don't do
* How many versions to keep in parallel - something package managers normally don't do
* Whether and when to update each application individually - something package managers normally don't do (sometimes, it's "all or nothing")

It is also part of the AppImage philosophy that the user can go to a download page of an application, and download the latest Linux version just along the Windows and macOS versions, so that an application author can just provide 3 downloads rather than 2 downloads (for Windows and macOS) and a list of instructions (for Linux).

AppImage is more closely related to how applications are used on macOS than how traditional Linux package management works, and this is by design.

Of course, optional tools like the optional `appimaged` daemon can be used; an automatic update functionality could be implemented there if someone volunteers.

**Comment by probonopd** [comment]
@TheAssassin is working on a "`appimageupdate.cpp`" that may, in the future, be integrated into AppImages to make them self-updateable.

**Comment by TheAssassin** [comment]
While checking the issues assigned to me, I dug out this old issue.

The rewrite of AppImageUpdate has begun a few weeks ago, and self-updating was always a goal for it. A prototype of this feature is available already (and has been implemented in AppImageUpdate's own AppImage, where we check for updates whenever an error occurs). We are working on making this feature available for third parties as well, I'll post a follow-up as soon as this is considered stable.

I'm closing this issue as we should move the discussion to the appropriate location, which is AppImageUpdate's repository. See https://github.com/AppImage/AppImageUpdate/issues/30.
