### ISSUE TITLE
command line arguments parsing

### ISSUE THREAD

**Issue by crayxt** [AppImage/AppImageKit#137]
When I supply file name of video as relative path in command line argument to AppImage file (VLC), it is treated as relative to appimage's internal file structure.
To make it work, one must specify absolute path of file

Also when file name in command line argument contains spaces, AppImage is not able to open it.

**Comment by RazZziel** [comment]
I've got a fix for that in PortableLinuxGames, I'll look for it hopefully this evening

**Comment by probonopd** [comment]
Yes @crayxt this is because in order to make some binaries relocateable, we patch `/usr` to `././` which means "the current directory". Hence we cd to the AppDir's usr/ before running the payload.

Cool @RazZziel looking forward to it.

**Comment by RazZziel** [comment]
Ok, first, I try to avoid using absolute paths instead of cd'ing in my AppRun as much as possible (see for instance this [generic AppRun](https://github.com/RazZziel/PortableLinuxGames/blob/master/data/AppRun_quick) for simple games)
However, because some apps need the binary to be run from a specific local directory and I need to cd, I have a script that turns all relative arguments in absolute arguments before cd'ing
```
. "$APPDIR/util.sh"

# Uncomment this if the app needs relative paths specified on the command line
eval arguments="$(patch_relative_paths "$@")"
set -- "${arguments[@]}"
```
The script is located [here](https://github.com/RazZziel/PortableLinuxGames/blob/master/data/util.sh#L158-L170) and you can see it in action [here](https://github.com/RazZziel/PortableLinuxGames/blob/master/data/AppRun_linker).

**Comment by probonopd** [comment]
Can you do this in C?

**Comment by RazZziel** [comment]
Thechnically, it shouldn't be a problem, it would be something like this:
```
    char *pwd = getenv("PWD");
    int pdw_len = strlen(pwd);
    int i;
    for (i=1; i<argc; ++i)
    {
        if (argv[i] != NULL && argv[i][0] != '/')
        {
            if (access(argv[i], F_OK) != -1)
            {
                char *new_arg = malloc(pdw_len + strlen(argv[i]) + 2);
                strcpy(new_arg, pwd);
                strcat(new_arg, "/");
                strcat(new_arg, argv[i]);
                argv[i] = new_arg;
                printf("+ %s\n", argv[i]);
            }
            else
            {
                printf("= %s\n", argv[i]);
            }
        }
    }
```

Which is executed before the line:
```
ret = chdir(path);
```

Output:
```
$ ./AppRun bleh blah md5.h ../AppImageKit/ derp

= bleh
= blah
+ /home/raziel/dev/AppImageKit/md5.h
+ /home/raziel/dev/AppImageKit/../AppImageKit/
= derp
```

The problem is:
* It only works on files that exist, that's the only way I have of knowing when to transform an argument. It would work in `vim existing_file_to_edit.txt` but not in `vim new_file_to_create.txt`
* It's a bit intrussive, as we're rewriting all the relative paths, and some app may not want that

**Comment by probonopd** [comment]
Thanks @RazZziel. I'd say, let's go for it' but I'd like to hear the opinion of others too. Maybe add a `--appimage-no-path-rewrite` option?

**Comment by shoogle** [comment]
This patch is a neat workaround, but when a binary cannot be relocated it should really be reported as a bug to the upstream developers. If upstream relies on absolute paths for locating resources that would normally be inside `/usr/share` then a 2-step solution [like this](https://github.com/musescore/MuseScore/pull/2362/files#diff-3056168911c88e142262cb695efd9fdaR217) can be used in the upstream code.

**Comment by probonopd** [comment]
Opinions on how we should proceed with this? The new `union: true` option for `.yml` files might mitigate the need for this, because when set, then no chdir is done...
