### ISSUE TITLE
Plan on making a Gnome Software plugin but...

### ISSUE THREAD

**Issue by PHPJosh** [AppImage/AppImageKit#244]
As the title states i plan on working on an Gnome Software plugin maybe in few weeks after i get my first ISO out of cinchOS but think we may need to implement Appstream some how into the kit. been looking at the source for Gnome Software and it seems it heavily depends on it to work properly.

I will start taking a look at it in my spare time up until i get my first ISO out but any Ideas in this area would be helpful :)

**Comment by probonopd** [comment]
AppStream is also [recommended by the AppImage spec](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#appstream). The AppStream developer is aware of AppImage and has recently added support for it to the `<bundle>` tag.

For the big picture, please read [Thoughts on an infrastructure for distributing Linux application bundles ](https://plus.google.com/105493415534008524873/posts/Z43MNMyPQW8)

**Comment by PHPJosh** [comment]
hmm so we will need to extract the Appdata out the AppImage and install it.. i will take a look at the desktop intergration and AppImage montior once i get done wrapping up on my first ISO as got about another week or so before i am done with that as still got quite a bit of packages to compile HAHA.

but from looking at the Gnome Software code the plugin will have to contain two parts. One to implement to Appstream parts of it then the second part for the actual sources for the AppImages which will probably use  your bintray sources first and later on I also plan on adding a App section to the soon to be Website for cinchOS that will be curated and it will be able to pull from that source also. I will also make it simple to add more to it.

then the other thing is I don't have a clue how to actually contribute to Gnome atm which i am reading in to now as once its done i for sure want to try to push it upstream as it will benefit everyone it it does. til then though will host a fork for  it at https://github.com/cinchOS/gnome-software/

**Comment by PHPJosh** [comment]
add about an extra week here as I have decided for the reasons of stability and so other issues with Arch (Packages being broken from get go when it comes to compiling them and other such issues, Rolling releases are Bad IMO) I am swapping to an Debain/Ubuntu Base and building from there. Not sure why i just didn't do this from start lol. other than i was using Arch when i got the Idea to build cinchOS rofl will post a status update once i get done swapping over which with it being Debain/Ubuntu should not take long

**Comment by probonopd** [comment]
This blog post by @hughsie outlines the GNOME Software (GS) plugin for Flatpak: https://blogs.gnome.org/hughsie/2016/07/05/flatpak-and-gnome-software/

> I wanted to write a little about how Flatpak apps are treated differently to packages in GNOME Software.

Let me go through this in detail because I suppose many of the concepts could be used in a very similar way to handle AppImages. Comments welcome!

> We’ve now got two plugins in master, one called flatpak-user and another called flatpak-system.

Maybe we need appimage-user and appimage-system then, too.

> Per-user applications that are specific to just a single user account are an amazingly useful concept, as most developers found using tools like jhbuild.

...and AppImage ;-)

> We default to installing software at the moment for all users, but there is actually a org.gnome.software.install-bundles-system-wide dconf key that can be used to reverse this on specific systems.

Then we should respect this key, too. AppImages are bundles just like Flatpak.

> We go to great lengths to interoperate with the flatpak command line tool, so if you install the nightly GTK3 build of GIMP per-user you can install the normal version system-wide and they both show in the installed and updates panel without conflicting.

There is no AppImage command line tool for installing. One simply downloads an AppImage, makes it executable, and is done with it. But to handle things like desktop integration, there is an optional `appimaged` daemon. This is what the GS plugin could communicate with.

> We’ve also got file notifications set up so GNOME Software shows the correct application state straight away if you add a remote or install a flatpak app on the command line.

How does this work? `appimaged` could notify GS in the same way.

> At the moment we show both packages and flatpaks in the search results, but when we suggest apps on the overview page we automatically prefer the flatpak version if both are available. In Ubuntu, snappy results are sorted above package results unconditionally

I tend to agree in that upstream-provided bundles are usually newer, and hence, preferred.

> ![](https://blogs.gnome.org/hughsie/files/2016/07/Screenshot-from-2016-07-05-14-45-35.png)

The same app is really shown twice in the search results. Why not show one search result, and on the product detail page show the different available versions and package/bundle formats? What if I have the system-provided package, a Flatpak, a Snap, a stable AppImage and two nightly AppImages of the same app? Is it then shown six times in the search results?

> GNOME Software also supports single-file flatpak bundles like gimp.flatpak – just double click and you’re good to install.

Now this is __very__ similar to AppImage. Just that if you double-click an AppImage, the app is launched rather than "good to install".

> These files are somewhat like a package in that all the required files are included and you can install without internet access.

Exactly like AppImage, which adds the benefit that the file does not have to be installed but can simply be run.

> These bundles can also install a remote (ie a reference to a flatpak repository) too, which allows them to be kept up to date. Such per-application remotes are only used for the specific application and not the others potentially in the same tree (for the curious, this is called a “noenumerate” remote).

For AppImage, we have [update information](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#update-information) embedded into the AppImage, which does the same thing. It is also only used for the specific application. Although an application author might have different channels like "releases", "nightlies", and so on, which would be embedded in the AppImages distributed through the respective channels.

> Each of these files contains all the metadata we need in AppStream format, with translations, icons and all the things you expect from a modern software center. It’s a shame snappy decided not to use AppStream and AppData for application metadata, as this kind of extra data really makes the UI really beautiful.

AppImage does, it's recommended [as per its spec](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#appstream).

I've also posted [thoughts on an infrastructure for distributing Linux application bundles](https://plus.google.com/105493415534008524873/posts/Z43MNMyPQW8) at length (tl;dr: A system to distribute Linux application bundles and exchange metadata about them is needed, and this writeup ponders on how to create the infrastructure needed for that).

> Just like the CLI, gnome-software can update flatpaks safely live (even when the application is running)

[AppImageUpdate](https://github.com/probonopd/AppImageKit/blob/master/AppImageUpdate.AppDir/README.md) does that too. But I think you still need to restart the application to benefit from the updated version, right? AppImageUpdate uses the `appimageupdate` command line tool (which is actually a shell script around [zsync-curl](https://github.com/probonopd/zsync-curl)). So we could probably invoke that from within GS and use the GUI provided by GS to signal the updates rather than the AppImageUpdate GUI.

While we are at it, I would also like to see [this](https://github.com/probonopd/AppImageKit/issues/256):

![](https://camo.githubusercontent.com/32e134dad89c67143cf75c994699df9b7333596c/687474703a2f2f7777772e6f6d677562756e74752e636f2e756b2f77702d636f6e74656e742f75706c6f6164732f323031362f30382f66697265666f782d333530783230302e6a7067)

> we do a little bit extra compared to the CLI and download the data we need to do the update when the session is idle and on suitable unmetered network access

How does this work? Does that mean it downloads the update before I even told the system to do so? Gosh do I hate that... eating away my precious RAM on a Live ISO system... (all I ever use are Live ISOs booted with [SystemImageKit](https://github.com/probonopd/SystemImageKit). Fully image based OSes without installation - OS can be upgraded or exchanged in under a minute).

**Comment by PHPJosh** [comment]
hmm this is a really informative read. I am almost done swapping over to Ubuntu Base and should have an ISO out soon as it super simple to make a Remix ISO on Ubuntu .. this all the initial ISO will be Remixed ISO at first just so i can get them out quicly and people can start seeing just how a Distro built around appimages will work with them being  upfront and center focus and not just an after thought.

so as soon as I start getting ISO out i plan on starting the Gnome software plugin. but seems I going to have to Update GTK+ for my distro as seems from reading some the new changes in the Plugin system only will work on 3.22 +

**Comment by probonopd** [comment]
As noted before, a special distribution is not needed... But of course you can do one if you like...

**Comment by probonopd** [comment]
@PHPJosh still interested in this?

**Comment by PHPJosh** [comment]
yes I am as I am back to working on things as took a break for awhile as was frustrated with the fact some people didn't realize I am not making my distro for us Power Users or everyday users of Linux  but new people. the people who come to Linux and get frustrated with it because in their eyes it doesn't "just work" like like windows or macOS. well past few days I have gotten confirmation there is a need for something like my idea so I have been reinvigorated to continue work on it. have to change things though as alot of software updates have changed stuff the past 10 or so months

**Comment by AsciiWolf** [comment]
Any news?

**Comment by probonopd** [comment]
@AsciiWolf we are still looking for a volunteer who would like to work on this. Is it you?

**Comment by AsciiWolf** [comment]
Sorry, I am not skilled in C. :-/

**Comment by probonopd** [comment]
@PHPJosh like to join us in working on https://github.com/probonopd/gs-plugin-appimage?

**Comment by azubieta** [comment]
closing as duplicated of #58
