### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [AppImage/AppImageKit#372]
I would like to point out that identifiers like “[`__ELFSIZE_H__`](https://github.com/probonopd/AppImageKit/blob/b178aa23546db6967ce73792157d0e2e89d4c4d2/elf.h#L16 "Update candidate")” and “[`__GETSECTION_H__`](https://github.com/probonopd/AppImageKit/blob/2824afc9e662fd6858fb5f1fa1f6d95a06bc8008/getsection.h#L1 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by probonopd** [comment]
Thanks for pointing this out. PR welcome.

**Comment by elfring** [comment]
Are there [a few update candidates left over](https://github.com/AppImage/AppImageKit/blob/347637ed5c68ddaea32f06933ffdca57dc8e060a/binreloc.h#L13 "Another update candidate")?

**Comment by TheAssassin** [comment]
You are totally right, there are some left. Reopened the issue.

We could and should think about moving to `#pragma once` though. It is way less error prone, well supported (GCC >= 3.4, which is really old) and generally nicer to read.

**Comment by elfring** [comment]
But [the construct “`#pragma once`” is not standard-compliant](https://en.wikipedia.org/wiki/Pragma_once#Caveats "Difficulties with usage of #pragma once").

**Comment by TheAssassin** [comment]
Well, to be honest, the "standards" you referred to about the naming of include guards is "just" a recommendation either. Technically the different meaning doesn't  change the way they work. If there's any benefit of changing them, then it's because some really outdated compiler on some esoteric platform might recognize them after the change and optimize the compiling process, but that's it.

On the other hand, most modern (I assume anything since GCC3 has had that) compilers recognize include guards in almost any form. So there's no real benefit of following the standard's recommendation, as we're most likely building on such a "new" (old) compiler platform and profit from these optimizations anyway.

The really big benefit comes when using the non-standard but, as written above, well supported `#pragma once`. There's no risk of cluttering with headers with the same name, one does not have to maintain the include guards on renames etc., just a single line instead of 3 spread across the file, ... and we are guaranteed to profit from specific optimizations I mentioned above.

Since not being standards compliant (which is rare in C/C++ anyway) is not likely to be problematic and greatly improves the usability, I don't see any point to avoid it. In fact in most work code I see include guards have been replaced by pragma once, and there's no problems, although the software is built for fairly "esoteric" platforms, too.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by TheAssassin** [comment]
Your link does not cover this case since undefined behavior can only occur during runtime due to the definition. As missing support of pragma once is definitely going to cause compilation errors, it is totally safe to use. A vast majority of C/C++ programmers and software engineers agree that pragma once is the way to go. If you want to, see it as a "pros overweigh cons" thing. Also, please ask yourself "if it wasn't a good thing, why wouldn't compiler issue warnings or refuse compilation?".

If you want to lecture others, please, don't paste in random links to questionable websites, and at least explain your point so the other person has a chance to understand your point. Another good idea was to include more details about which part of the reference you actually refer to. I had to guess it's no. 97 in that table, which does not apply as far as I can see.

Also, if you want to talk about undefined behavior, please post a full analysis of the source code and have us discuss this in another issue (separation of concerns), as there's most likely more of it to be fixed. This started primarily as an opinion related feature proposal, there's no actual technical requirement to perform the change.

May I ask you for a PR so we can close this issue? You have proved you're good at spotting these. I don't particularly dislike include guards if they are done properly, but don't want to modify them and would rather replace them instead, but would happily merge a PR which fixes them.

**Comment by elfring** [comment]
>… undefined behavior can only occur during runtime due to the definition.

I find this view questionable and incomplete.

The application of [the construct “`#pragma once`” contains its own risks](https://stackoverflow.com/questions/1695807/why-isnt-c-cs-pragma-once-an-iso-standard#answer-1696194 "Why isn't C/C++'s “#pragma once” an ISO standard?").


>I don't particularly dislike include guards if they are done properly, but don't want to modify them …

@probonopd adjusted two include guards already. I hope that [tampering with the reserved name space](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") can be reduced further if a corresponding consensus can also be achieved.

**Comment by TheAssassin** [comment]
And again, your reference is as biased as this discussion, and one can find both opinions in there. Stack Overflow is not representative, especially with all the duplicate discussions. I feel that you just picked one whose most upvoted reply supports your point of view, and thus this reference is pretty useless to support your argumentation.

Both approaches have their downsides, include guards being a dirty and also not standardized but recommended hack rather than a solution, and pragma once which is not standardized but less hackish, less ambiguous for the user (software developer using them), and being supported on any but the most esoteric platforms.

I already intended that if someone fixed the rest in 
a PR, it would be merged and the issue was solved. 

Asking for others to perform changes which mostly change things to their own mind is not polite. Thus, please send a PR that fixes the rest, and we're all happy afterwards.

**Comment by TheAssassin** [comment]
By the way, I have to agree that the double underscores are reserved. I admit that for this reason, the include guards should be changed. I didn't think of that until you mentioned it.

**Comment by elfring** [comment]
I find it interesting that you can agree to such a consequence when you care also about specifications for reserved name spaces from the referenced standard documents.
Now I am curious who would like to pick remaining change possibilities up.

**Comment by probonopd** [comment]
If I could have a wish for a language, it should not have any undefined behavior... 💯

**Comment by darealshinji** [comment]
Wait, isn't `__cplusplus` actually a reserved identifier? https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html

**Comment by TheAssassin** [comment]
Well, according to the link it is. Why do you mention it?

**Comment by darealshinji** [comment]
Sorry, I should have pointed out that @probonopd "fixed" it too: https://github.com/AppImage/AppImageKit/commit/c6ad421827711359799f7763876d525b2e75c0d4#diff-4080f181ea85b1e712299f597dcf7d9bL27

**Comment by TheAssassin** [comment]
Ah, I see. That has to be fixed ASAP.

**Comment by probonopd** [comment]
A lot of time invested into this. Did it actually bring us any functional or stability benefit?

**Comment by elfring** [comment]
How much do you care for standard compliance?

**Comment by probonopd** [comment]
First and foremost I care about things working ;-) So it it's broken (as in: there is a bug), then I care.

**Comment by elfring** [comment]
There are special cases where you can occasionally break something because the needed knowledge was incomplete (to some degree).

**Comment by TheAssassin** [comment]
As far as I'm concerned, this issue can be closed.

And yes, as long as it works as intended, standards compliance is not necessarily required and often not worth the effort, especially when the non-standard directives are well supported. And for directives such as `#pragma once` the behavior that can be expected on platforms that do not support it is quite foreseeable (a lot of redefinition errors, as the directive is just ignored, and any more or less experienced C(++) programmer should be able to recognize the cause, no undefined behavior), thus they are really really safe to use. All these special cases you refer to are really esoteric platforms, AppImage doesn't have to run on any Amiga platforms or something like that, and even there, there would just be compiler errors. I guess you couldn't even get FUSE to work there.
