### ISSUE TITLE
[Release 5] AppImageAssistant needs libpng12.so.0

### ISSUE THREAD

**Issue by GarethH96** [AppImage/AppImageKit#397]
The latest stable release of AppImageAssistannt (v5 currently) won't run without libpng12.so.0. I am on Ubuntu 17.04, using libpng16.so.0. I tried installing the .deb of  the older version, but unable to so due to conflicts.

**Comment by TheAssassin** [comment]
Please post a log of your execution. I am not aware of any changes leading to the need of libpng inside AppImageAssistant (especially since AppImageAssistant has kinda been abandoned, due to AppImage v2 and appimagetool being recommended now). I highly doubt that's the actual issue.

If possible, consider switching to v2 AppImages and appimagetool. We might drop support for AppImageAssistant soon.

**Comment by GarethH96** [comment]
Here is the error message:
`Traceback (most recent call last):
  File "/tmp/.mount_RBTg3S/AppImageAssistant", line 87, in <module>
    import  gtk, vte
ImportError: libpng12.so.0: cannot open shared object file: No such file or directory
`

**Comment by probonopd** [comment]
Hi @GarethH96 would using `appimagetool` instead of AppImageAssistant be an option for you?

**Comment by probonopd** [comment]
AppImageAssistant is deprecated.
