### ISSUE TITLE
AppImage installs the .desktop file but not the icon

### ISSUE THREAD

**Issue by mjmacleod** [AppImage/AppImageKit#402]
I'm generating a basic AppImage from a .yml file that I've based off other .yml file examples.
When the AppImage 'integrates' with the system the .desktop file ends up in the right place but no icon is installed.

https://pastebin.com/kGtriQjf

If I instead copy the png files into the usr/share directory then it works as expected.

https://pastebin.com/zy1yw2Qi

**Comment by probonopd** [comment]
Yes, putting the icons into the various usr/share/icons/hicolor/ subdirectories is the correct way to go.

**Comment by TheAssassin** [comment]
Well, I'm not sure if we shouldn't just accept desktop files in the AppDir root, too, though. It sounds like a good idea to do so to me.

**Comment by mjmacleod** [comment]
I'm happy to just put them in the subdirectories, as that works for me.

Though I'll note that various documentation that is scattered around (including some of the sample yml files - like the gitkraken one) make it appear like the other way (just the one image in the root) should work.
In the interests of clarity, for future people, it might be good to make it a bit more clear that this doesn't work and state explicitly somewhere that an icon is required in at least one of the usr/share/icons/hicolor/ directories in order for it to work.

**Comment by probonopd** [comment]
> When the AppImage 'integrates' with the system the .desktop file ends up in the right place but no icon is installed.

Which method did you use to integrate with the system? The script embedded inside the AppImage (the one that opens a dialog box asking whether it should integrate into the menu) or the optional `appimaged` daemon?

Some explanation:

These two things _could theoretically_ be updated to fallback to icons in the root directory if they don't find icons in `usr/share/icons` subdirectories. __But__ also see https://github.com/probonopd/AppImageKit/issues/258#issuecomment-271186247. Some desktops insist on icons being in a subdirectory that bears the size in pixels since they apparently are not able to figure out the icon size on their own. So either we add logic to `appimaged` that determines the icon size on-the-fly and copies the icon to the appropriately named subdirectory, or we ask the user to put the icons into the appropriately named directories inside the AppDir in the first place. Right now we are doing the latter.

**Comment by probonopd** [comment]
Please point to misleading documentation, or even better, please send pull requests on the misleading documentation and examples. Thanks!

**Comment by mjmacleod** [comment]
"Which method did you use to integrate with the system? The script embedded inside the AppImage (the one that opens a dialog box asking whether it should integrate into the menu) or the optional appimaged daemon?"

The embeded script.

"Please point to misleading documentation, or even better, please send pull requests on the misleading documentation and examples. Thanks!"

https://github.com/probonopd/AppImageKit/wiki/AppImages  (all yml links broken by the way) links various sample yml files like https://github.com/probonopd/AppImages/blob/master/recipes/meta/GitKraken.yml which only put the one icon in the root and therefore have the same problem.

I think there may have been some other documentation which also gave the idea, but can't remember it offhand and don't have the time to relook at all of it.

Unfortunately don't have any time to contribute, sorry, so I'll leave it there. Just thought I'd mention the experience in case it is of any benefit to others. Thanks!

**Comment by probonopd** [comment]
Thanks for pointing this out @mjmacleod

**Comment by TheAssassin** [comment]
As usual, PRs welcome.

**Comment by azubieta** [comment]
This issue is related to the desktop integration script which is deprecated. Closing the issue.
