### ISSUE TITLE
Appimage appears to launch without error, but no window is ever launched.

### ISSUE THREAD

**Issue by shaunmulligan** [AppImage/AppImageKit#409]
**Issue** 
AppImage fails to launch the app window, but doesn't throw any errors.
While trying to install the https://etcher.io/ Appimage the AppImage appears to run correctly with no errors, but the etcher app is never launched on my desktop. cc @jviotti the maintainer of etcher

manually mounting the AppImage and running `/mnt/AppRun` works as expected and the etcher UI is visible.

**Operating system**
NAME="openSUSE Tumbleweed"
VERSION="20170602"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="20170602"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20170602"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

**Comment by TheAssassin** [comment]
The AppImage project cannot provide support for third-party AppImages. You posted this at the wrong issue tracker unfortunately. Please file an issue at etcher's bugtracker.

The AppImage project just provides the tools for software developers to distribute their applications as AppImages. Please see our [README](https://github.com/AppImage/AppImageKit/blob/master/README.md) for more information on the purpose of this repository.

If you can prove that it's a problem with software found in this repository (e.g. appimagetool or AppRun), then please reopen this issue and provide detailed information not just on your system but the character of your bug.

**Comment by probonopd** [comment]
Please try to run from the command line and watch for any error messages there.

Do you have a working FUSE setup? FUSE is known to be broken in Tumbleweed at the moment.
https://github.com/AppImage/AppImageKit/wiki/FUSE

**Comment by shaunmulligan** [comment]
@TheAssassin and @probonopd I was directed here from etcher. I can launch etcher correctly if I follow https://github.com/AppImage/AppImageKit/wiki/FUSE#fallback , hence the reason I suspect the issue may be with the interaction with OpenSuse and the Appimage rather than an issue with etcher.

If I run `./Etcher.AppImage` there is no out put.

**Comment by probonopd** [comment]
By the way, it is easy to fall into the trap of downloading the "x86" (= 32-bit) version. 90% of users are running 64-bit these days. So you need to download the 64-bit AppImage from the website. @jviotti maybe you can make 64-bit the default or even parse it from the browser's user agent string.

**Comment by probonopd** [comment]
Can you run other AppImages? For example, can you run Leafpad from http://download.opensuse.org/repositories/home:/probono/AppImage/?

**Comment by TheAssassin** [comment]
@shaunmulligan okay, but I am not sure if this is a bug of AppImageKit.

To check if the FUSE setup is working please try to run it with `--appimage-mount` and see if it tells you that it mounted it somewhere in `/tmp`. Then you can investigate the contents further in that directory, similar to the root mount. This is probably a more reliable test than trying to run other AppImages, although that's a good idea, too. Mounting the way you did before does not use FUSE, which is required to run it as a normal user, thus that doesn't tell us much.

I doubt an i386 AppImage will run without the according FUSE libraries being installed as i386, too, it'd result in some linker errors. Only the contents of the AppImage could crash without any notice. But I doubt that, since it works when @shaunmulligan runs it when mounted manually.

**Comment by shaunmulligan** [comment]
@TheAssassin and @probonopd thanks for the quick responses and sorry for the trouble, I noticed the small note about having to run the additional `chmods` on /usr/bin/fusemount in this page https://github.com/AppImage/AppImageKit/wiki/FUSE#install-fuse

Sorry for the noise and thanks for the help :+1:

**Comment by TheAssassin** [comment]
You're welcome. If you feel the documentation should be updated so this gets more clear, you're free to edit the wiki page.

**Comment by probonopd** [comment]
You're welcome, and spread the word on AppImage!
