### ISSUE TITLE
appimaged: doesnt scan .hidden dirs under home directory for appimages?

### ISSUE THREAD

**Issue by star-buck** [AppImage/AppImageKit#415]
would be a feature request to do if it doesnt.

**Comment by probonopd** [comment]
For performance reasons, it only scans defined directories. `$HOME/.local/bin` is among these. Which others should be added?

Relevant code:
https://github.com/AppImage/AppImageKit/blob/adaf3c5a2576da78d7268836c02f04c0106149d9/appimaged.c#L307-L315

**Comment by star-buck** [comment]
.bin and .appimages would be great.

**Comment by probonopd** [comment]
Don't really like `.appimages` because it gives the impression that they need special treatment, compared to all other executable files (a.k.a. "bin"). Will add `$HOME/.bin`. But not sure that hiding the files from the user's view is a good idea, since there is no package manager, and users are supposed to interact with (e.g., delete) the files themselves directly. So `$HOME/bin` may be a better choice. On openSUSE systems, there is even a `$HOME/bin` directory by default.
