### ISSUE TITLE
Noticing poorer preformance on AppImages

### ISSUE THREAD

**Issue by hcorion** [AppImage/AppImageKit#426]
We've noticed poorer performance with AppImages versus self compiled binaries, using the same compiler (clang 4.0), with no additional flags.
We're using probonopd's linuxdeployqt, to create the appimage, you can see the travis code here: https://github.com/RPCS3/rpcs3/blob/master/.travis.yml#L80-L95

Would it perhaps be the issue of Ubuntu Trusty's old libraries?
We're a PS3 emulator, so testing for you might be kind of difficult.

You can check out the AppImage here: https://rpcs3.net/cdn/builds/rpcs3-v0.0.2-2017-07-04-78fad1a-7024_linux64.zip

**Comment by probonopd** [comment]
What do you mean by "poorer performance", can you share your measurements?

**Comment by probonopd** [comment]
Please also see https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages#common-mistake.
Please don't put AppImage files into another archive like a zip.

**Comment by hcorion** [comment]
I was able to achieve 17-20 FPS in the self-compiled binary, but only achieved about 10 FPS - 15 FPS on the AppImage. A difference of only 5 FPS might not seem like much, but when FPS is that low, every frame counts.

**Comment by TheAssassin** [comment]
As the maintainer of a game AppImage, I can tell you that the general performance is not affected by the AppImage itself at all. If there is a problem, it's caused by the contents, not by the fact it's run as an AppImage.

Some of the libraries contained in the AppImage are worrying. Especially libGL* and some of the libX* libraries most likely cause your performance loss.

As a simple test and to verify it's not the AppImage runtime itself (which, in fact, just FUSE-mounts the contents somewhere, modifies LD's paths and calls the binary in there, it's really minimal), please build a new AppImage that does not bundle any libraries but uses the system ones instead, like a regular binary. 

Just run the same steps like on trusty to create an AppImage with the libraries, then call it with `--appimage-extract`, go to the extracted directory `squashfs-root` and remove all the libraries in `usr/lib/` in there. Next, use appimagetool to create the new one, e.g. by runnig `cd .. && appimagetool squashfs-root new.AppImage` and run that one for comparison. It should run with the exact same performance.

And yes, trusty is a really bad platform choice since it is no longer supported (since April 2017). You're likely to put in libraries that you will never receive updates for. Before releasing AppImages, consider switching to some distro that is as old as trusty but still updated. We currently recommend the latest release of CentOS 6.

If you really need to bundle some X or GL libraries, you should consider building newer versions yourself during the build. This might be quite some more effort, but will result in the best performance and thus a better user experience.

**Comment by hcorion** [comment]
Was a stupid mistake, closing. For some reason we were using -O1 for travis builds.
