### ISSUE TITLE
Recognize that app was built as an appimage

### ISSUE THREAD

**Issue by luzpaz** [AppImage/AppImageKit#429]
We want FreeCAD to recognize that it's been built as an appimage.
For example: 
```
OS: "Manjaro Linux"
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.10600 (Git)
**Build type: None**
Branch: master
Hash: 4d9169faf778e9716fc647fb3fcf46462b5d99a4
Python version: 2.7.6
Qt version: 4.8.6
Coin version: 4.0.0a
OCC version: 7.1.0
```
**Build type:** should state **appimage**. So what needs to happen in the build process for us to recognize this? I'm asking not for you to understand the FC internals...but in general have you seen this before in other applications ?

So I'm referencing a downstream FreeCAD build ticket: https://freecadweb.org/tracker/view.php?id=2987
and the thread it's from: https://forum.freecadweb.org/viewtopic.php?f=10&t=15525&p=182279#p182279

**Comment by TheAssassin** [comment]
You just have to check for the environment variable `APPIMAGE`, it's set to the path of the AppImage file. The variable is set by the AppImage runtime, so if someone extracts the AppImage and uses it from the AppDir directly (like, the libraries in there are used as well), the AppImage runtime is obviously not in use and thus the environment variable is missing. But I guess that's just an edge case, I think it should suffice to check for the environment variable.

A better approach would be to define a macro using a compiler flag or something like that, so that it doesn't matter any more whether the AppImage runtime is used or not. I use a similar approach in my Red Eclipse AppImages: I have to use a custom AppRun script to mitigate some limitations of the current binary (just a workaround until I get to fix that), which sets a special environment variable and thus doesn't depend on `APPIMAGE`, so it is set for extracted AppImages, too.

**Comment by luzpaz** [comment]
CC @looooo 
can we do something like this on travis?

**Comment by looooo** [comment]
Maybe @triplus.

**Comment by probonopd** [comment]
Closing this since I think @TheAssassin has answered this from an AppImage perspective.

**Comment by luzpaz** [comment]
> A better approach would be to define a macro using a compiler flag or something like that, so that it doesn't matter any more whether the AppImage runtime is used or not. I use a similar approach in my Red Eclipse AppImages: I have to use a custom AppRun script to mitigate some limitations of the current binary (just a workaround until I get to fix that), which sets a special environment variable and thus doesn't depend on APPIMAGE, so it is set for extracted AppImages, too.

@TheAssassin can you point out the code where you did this ?

**Comment by TheAssassin** [comment]
This place in the launcher script: https://github.com/TheAssassin/redeclipse-appimage/blob/master/AppRun#L3

The script is copied and patched here: https://github.com/TheAssassin/redeclipse-appimage/blob/master/build-appimages.sh#L183
