### ISSUE TITLE
Get rid of the zlib dependency

### ISSUE THREAD

**Issue by RazZziel** [AppImage/AppImageKit#5]
zlib is ubiquitous, but it's a potential portability problem, and can be easily avoided linking statically: http://pastebin.com/GJJ3qjxM

Overhead in the runtime binary is about 32Kb

**Comment by TheAssassin** [comment]
Looks like this issue was about AppImage type 1, which has been obsoleted by type 2 and appimagetool.

Thus I can think it can be closed, too.

Please note that the note about pastebin links in issue trackers https://github.com/AppImage/AppImageKit/issues/4#issuecomment-306229156 applies to this issue, too.
