### ISSUE TITLE
Where does appimage save the setting of my apps?

### ISSUE THREAD

**Issue by JulianLai** [AppImage/AppImageKit#506]

**Comment by TheAssassin** [comment]
I'll have to make a guess, since the information you provide is just too little.

It doesn't make a difference whether you run an application in an AppImage or not in general, the application has access to the normal system, there is no sandboxing.

The only difference could be that the application in the AppImage might modify the current working directory.

Closing as invalid. Feel free to reopen with more information.

**Comment by JulianLai** [comment]
The linux operating system saves their application config file in ~/.config, but I don't know where the appimage save their app config file without the sandbox.

**Comment by TheAssassin** [comment]
> The linux operating system saves their application config file in ~/.config

That's got nothing to do with Linux (or even your distribution of it, which you should call your OS since those distributions vary highly), applications decide where to store their data, and that's usually `~/.config` or `~/.local/share` as FreeDesktop standards suggest.

> Are they using the same location?

There are no standard rules about AppImages, and where they store data. As said before, an AppImage works like the any other normal application, the runtime itself does not make a difference except for the current working directory, but any sane app will not rely on that for storing configuration data. The only real differences could be created by the packager creating the AppImage. But without telling more information, there is no chance of being able to help you. In general, I'd say yes.

Since you don't provide the standard information, I'll give you a list:

  - distribution name and version
  - what application (ideally with a link to the AppImage)

However please expect us to say "you'll have to contact the AppImage author", as we cannot provide support for third party applications, we'd only have a look if the issue was created by the AppImage runtime or other AppImage provided tools.
