### ISSUE TITLE
`appimagetool-x86_64.AppImage --appimage-portable-{home,config}` does not work

### ISSUE THREAD

**Issue by KurtPfeifle** [AppImage/AppImageKit#539]
I was just now having a look at the latest version of *`appimagetool`*. Here is the result:

<pre>
./appimagetool-x86_64.AppImage --appimage-portable-config
   Error creating portable config directory at /proc/self/exe.config: No such file or directory

./AppImages/appimagetool-x86_64.AppImage --appimage-portable-home                                                       
  Error creating portable home directory at /proc/self/exe.home: No such file or directory                                                   
</pre>

Is this supposed to work already? Or still work in progress?

----

I'm also not sure HOW it is supposed to function: Create the directories if they do not exist? Report their location *IF* they exist?

Also the following output for *`--appimage-help`* is not clear to me:

<pre>
  Portable options:

    If you want the AppImage to use a portable $HOME or $XDG_CONFIG_HOME, you can 
    use the --appimage-portable options or create the following directories manually: 

    My.AppImage.home will be used as $HOME
    My.AppImage.config will be used as $XDG_CONFIG_HOME 
</pre>

Does it say there is another parameter, *`"--appimage-portable"`*? Or is it the following what should be expressed?

<pre>
  Portable options:

    The parameter '--appimage-portable-home' will create a directory with the exactly
    same name as the AppImage file, but with an additional '.home' suffix. The starting,
    running and exiting AppImage will treat this directory as the $HOME of the user.

    The parameter '--appimage-portable-config' will create a directory with the exactly
    same name as the AppImage file, but with an additional '.config' suffix. The starting,
    running and exiting AppImage will treat this directory as $XDG_CONFIG_HOME.
 
    If you want the AppImage to use a portable $HOME or $XDG_CONFIG_HOME, you can 
    use the --appimage-portable options or create the following directories manually: 
</pre>

**Comment by probonopd** [comment]
The text `--appimage-portable` is misleading. There is no such option. `--appimage-portable-*` is meant, referring to `--appimage-portable-home` and `--appimage-portable-config`. We could even think about dropping the latter (or hiding it from users at least) since `-home` is what 99% of users will need (and understand).

**Comment by pamarcos** [comment]
How about this? I just modified the length of the right column to fit Ubuntu's default terminal size

```
AppImage options:

  --appimage-extract              Extract content from embedded filesystem image
  --appimage-help                 Print this help
  --appimage-mount                Mount embedded filesystem image and print
                                  mount point and wait for kill with Ctrl-C
  --appimage-offset               Print byte offset to start of embedded
                                  filesystem image
  --appimage-portable-home        Create a portable home folder to use as $HOME
  --appimage-portable-config      Create a portable config folder to use as
                                  $XDG_CONFIG_HOME
  --appimage-signature            Print digital signature embedded in AppImage
  --appimage-updateinfo[rmation]  Print update info embedded in AppImage
  --appimage-version              Print version of AppImageKit

Portable options:

  If you want the AppImage to use a portable $HOME or $XDG_CONFIG_HOME, you can
  use the --appimage-portable-[home|config] options or create the following
  directories manually:

  My.AppImage.home will be used as $HOME
  My.AppImage.config will be used as $XDG_CONFIG_HOME

```

**Comment by probonopd** [comment]
Should explicitly say that it is __not__ needed to specify `--appimage-portable-` to __use__ these directories (they will be used if they are present) and that the options _cannot_ be combined

**Comment by pamarcos** [comment]
Ok, what about

```
Portable options:

There is support to have a portable $HOME and $XDG_CONFIG_HOME for a specific
AppImage. To do so, you can either create a directory as follows:

  My.AppImage.home will be used as $HOME
  My.AppImage.config will be used as $XDG_CONFIG_HOME

Or you can use --appimage-portable-home to create a portable $HOME directory
or --appimage-portable-config for a portable $XDG_CONFIG_HOME. These options
cannot be used at the same time
```

**Comment by probonopd** [comment]
Honestly, while technically accurate, our target group end user will not understand this.
Let's not mention  $XDG_CONFIG_HOME nor --appimage-portable-config, and let's write a description that my grandma will understand.

"If you would like the application contained inside this AppImage to store its data alongside this AppImage rather than in your home directory, then..." or something like that.

@TheAssassin will vividly remember that we had a user asking for a "portable apps feature" but did not grasp the concept of what "export $HOME" means.

**Comment by pamarcos** [comment]
Sure, just tell me exactly what you want to say and I'll throw that into the source code

**Comment by TheAssassin** [comment]
@probonopd well, I'd leave the indented part explaining the technical details (like, to not promise too much, @pamarcos is right there), but we should be able to find a simpler wording for the text blocks.

**Comment by probonopd** [comment]
Suggestion:

If you would like the application contained inside this AppImage to store its data alongside this AppImage rather than in your home directory, then you can place a directory named _print the name of the directory here, using the real path and name of THIS AppImage_. Or invoke this AppImage with the --appimage-portable-home option, which will create this directory for you. As long as the directory exists and is neither moved nor renamed, the application contained inside this AppImage to store its data in this directory rather than in your home directory.

@KurtPfeifle can you please have a look to make sure that the text is really clear and understandable to a person who does not know about the concept of "export $HOME"?

**Comment by TheAssassin** [comment]
The portable apps feature will work for many apps, but it is not guaranteed. I think the "real" portable apps promise full isolation (worded like "does not leave traces" or so), but I am not even sure if they do any different. However, if there were any traces left by an AppImage (and I know a bunch which don't make use of `$HOME` and `$XDG_*`, and the temporary directories on Linux are meant for all users), we'd easily promise too much here.

**Comment by pamarcos** [comment]
It's not as easy as it seems to find the proper balance into explaining this properly so that people see the difference with a sandboxed application without being too pedantic.

**Comment by probonopd** [comment]
I think that 

> store its data alongside this AppImage rather than in your home directory

is adequate and not over-promising. It doesn't claim to change anything about data that normally goes outside of the home directory. We are also not claiming anything about isolation nor "no traces", which fall more into the Sandboxing domain (which PortableApps.com also didn't enforce last time I checked).

**Comment by TheAssassin** [comment]
However, it states that _all_ the data would be stored there, but we can not guarantee that. This needs to be reflected in the description.

**Comment by pamarcos** [comment]
![image](https://user-images.githubusercontent.com/3248441/33102304-6dd9f976-cf1c-11e7-926a-3c3d492fcf79.png)
The only issue I see is that we can't foresee the length of the AppImage name we use in this string and so that line might be too long. Apart from that, should we display the fullpath.home or only the filename.home?

**Comment by probonopd** [comment]
Let's make the line with the path to the AppImage on its own line, so that it has the full 80 characters. However it seems to not print the full absolute path for me when the AppImage was invoked with a relative path:

![screenshot](https://user-images.githubusercontent.com/2480569/33113193-54ffa0d2-cf57-11e7-9399-df7f1535e0d1.png)

**Comment by TheAssassin** [comment]
@pamarcos there is an easy algorithm to wrap a string dynamically based on a maximum width. You basically search for every 80th character, then look backwards from that position to find the next space character, replace it with a newline character, and then look for the 80th character from there and repeat the procedure. If you can't find a character in a reasonable distance, you can just break it. I use half a line (i.e., 41 characters) as the limit. This algorithm can be implemented recursively in just a few lines. If you want to, I'll make the adjustments.

**Comment by pamarcos** [comment]
Go ahead. Of course it can be done, but I don't know if it's worth the effort, to be honest

**Comment by probonopd** [comment]
I don't think that splitting paths over 80 characters is a good idea since it makes copy and paste (which I do all the time in the terminal) unnecessarily hard. It's OK for a long path to  wrap around.

**Comment by TheAssassin** [comment]
Now that #540 is merged, can we close this issue? CC @probonopd

**Comment by probonopd** [comment]
Yes, closing here. In case something still needs to be changed, let's open a new issue. Thank you very much for your patience @pamarcos and @TheAssassin
