### ISSUE TITLE
problem with APPDIR env var and patched-away "usr"

### ISSUE THREAD

**Issue by darealshinji** [AppImage/AppImageKit#554]
Consider the following C++ code where a program makes use of the APPDIR environment variable:
``` C++
std::string appdir_var = get_environment_variable("APPDIR");
if (appdir_var.empty())
  locale_dir = DEFAULT_PREFIX + "/share/locale"
else
  locale_dir = appdir_var + "/usr/share/locale";
```
The `usr` inside the string `/usr/share/locale` would get patched away and the program would try to look for `APPDIR/share/locale` which doesn't exist.

Possible solutions for this:
 * always append `usr` to APPDIR
 * create another environment variable, i.e. APPDIRUSR
 * rename the prefix inside the AppImage to i.e. `data` and change the AppRun source accordingly

**Comment by TheAssassin** [comment]
@darealshinji just a little tip, checking for `APPDIR` to be empty is maybe not the best way, I always check whether `getenv()` returns a nullpointer (in which case it is not set), too. Being empty (i.e., being set to a string with length 0) and being not set are two really different cases which should be handled separately (`$APPDIR` being unset at all means that you're not running from the AppImage runtime in most cases, `$APPDIR` being set to an empty or otherwise invalid path is really a bug that should be reported).

That said, appending `/usr` to `$APPDIR` would change its meaning. Currently, it points to the mount point, and nothing else.
(Binary patching is not at all recommended anyway (rather try to use linuxdeployqt).)
f I had to pick an option, I'd go for the second one, setting another environment variable, that's the safest way, keeps everything backwards compatible (won't break older applications relying on `APPDIR` being set directly to the mount point), etc.

**Comment by probonopd** [comment]
AppImageKit doesn't patch anything away.

**Comment by darealshinji** [comment]
@TheAssassin This was just an example and note that `get_environment_variable()` is not `geten()` but thanks anyway for the tip.

@probonopd Should I have opened it in AppImage/AppImages? It's related to `patch_usr()` from `functions.sh`.

**Comment by probonopd** [comment]
> @probonopd Should I have opened it in AppImage/AppImages? It's related to patch_usr() from functions.sh.

Yes. But a recipe should simply not call patch_usr() if it is working on an application that is already relocatable. So I don't think there is an actual issue there.

**Comment by probonopd** [comment]
> I guess another workaround in the source code might be to use sprintf() kinda like this: sprintf(var, "%s/%s/share/locale", appdir, "usr")

Better just use the appropriate XDG environment environment variables instead of hardcoding paths in the first place.

**Comment by azubieta** [comment]
I guess that we can close this issue, please reopen it if required.

**Comment by probonopd** [comment]
A program should not really make use of the `APPDIR` environment variable, since it would break as soon as the AppDir is extracted from the AppImage. Applications should instead use paths relative to the main binary, e.g., using [binreloc](https://github.com/limbahq/binreloc).
