### ISSUE TITLE
return value of AppRun

### ISSUE THREAD

**Issue by darealshinji** [AppImage/AppImageKit#558]
Right now AppRun seems to return 1 on error and 0 on success. But shouldn't it return the return value of the forked app on success?

``` C
  int errsv, status;
  ret = execvp(exe, outargptrs);
  errsv = errno;

  if (ret == -1)
    die("Error executing '%s'; return code: %d\n%s\n", exe, errsv, strerror(errsv));
  else if (pid > 0 && waitpid(pid, &status, 0) > 0 && WIFEXITED(status) == 1)
    ret = WEXITSTATUS(status);

  [...]
  return ret;
```

By the way the value of `ret` here is always `-1`, no point to use `return code: %d`:
``` C
  if (ret == -1)
    die("Error executing '%s'; return code: %d\n", exe, ret);
```

**Comment by probonopd** [comment]
You are correct. Can you send a PR please? Thanks.

**Comment by TheAssassin** [comment]
@darealshinji sorry, but that doesn't really make sense to me.

See https://linux.die.net/man/3/exec. The `exec()` family *only* returns in case an error occurs while trying to execute the process (in which case it sets `errno` and returns `-1`, which is *not* the return code of the newly executed process), otherwise, it won't ever return (program flow wise). The executed process replaces the current process, i.e., the old process will *never* see the original process's return code. I don't see the issue here at all. The currently implemented behavior seems to be correct. Please elaborate.

The only case in which all the `waitpid()` stuff would make sense is when AppRun would `fork()` and keep running in the background. But this is not the case.

@probonopd please do not merge #559 for now.

**Comment by darealshinji** [comment]
Sorry, my mistake. AppRun is indeed behaving correctly.
But I guess you could still change the following part:
``` diff
   if (ret == -1)
-    die("Error executing '%s'; return code: %d\n", exe, ret);
+    die("Error executing '%s'; return code: -1\n", exe);
```

**Comment by TheAssassin** [comment]
Yes, you're right, but I'd even remove the whole return code thingy.
