### ISSUE TITLE
Use of wildcard character in 'updateinfo' strings

### ISSUE THREAD

**Issue by KurtPfeifle** [AppImage/AppImageKit#637]
My little 'selftests.sh' script which looks at different aspects of the AppImages released as tools by the AppImage project just now revealed to me the following table:

````

 ================================
    Running check_updateinfo:
 ================================
             appimaged :  gh-releases-zsync|AppImage|AppImageKit|continuous|appimaged-x86_64.AppImage.zsync
        AppImageUpdate :  gh-releases-zsync|AppImage|AppImageUpdate|continuous|AppImageUpdate-*x86_64.AppImage.zsync
    appimageupdatetool :  gh-releases-zsync|AppImage|AppImageUpdate|continuous|appimageupdatetool-*x86_64.AppImage.zsync
          appimagetool :  gh-releases-zsync|AppImage|AppImageKit|continuous|appimagetool-x86_64.AppImage.zsync
         linuxdeployqt :  gh-releases-zsync|probonopd|linuxdeployqt|continuous|linuxdeployqt*-x86_64.AppImage.zsync
                zsync2 :  gh-releases-zsync|AppImage|zsync2|continuous|zsync2-*x86_64.AppImage.zsync
            zsyncmake2 :  gh-releases-zsync|AppImage|zsync2|continuous|zsyncmake2-*x86_64.AppImage.zsync
````

As you can notice, the updateinfo strings use in part a '\*'-wildcard for the respectiv .zsync filenames, in part no such wildcard:

- without '\*'-wildcard: *`appimaged`*, *`appimagetool`*
- with '\*'-wildcard: *`appimageupdatetool`*, *`AppImageUpdate`*, *`linuxdeployqt`*, *`zsync{,make}2`*

Maybe you want to re-evaluate each case of using of wildcards or not, and make it more consistent?
(also in the context of issue #635)?

----
<sup>(NOT reporting this to the linuxdeployqt and AppImageUpdate projects for now...)</sup>

**Comment by TheAssassin** [comment]
What exactly are you complaining about here? See https://github.com/AppImage/AppImageSpec/blob/master/draft.md#github-releases. This doesn't have anything to do with consistency. It's a technical necessity to use "wildcards" for appimageupdatetool etc., because those filenames change with every new release (they contain a version number).

As explained in #636, this won't change. And we are not going to remove wildcard characters, as then the updates won't work any more. And it doesn't make sense to introduce wildcard characters for appimagetool and linuxdeployqt because then it "looks more consistently".

I don't see an issue.

P.S.: Sentences like

> (NOT reporting this to the linuxdeployqt and AppImageUpdate projects for now...)

... do you want to state that you're too lazy to report those issues in the right projects? It is an annoying task for maintainers to create the issues in the right projects (if there are any), that just keeps us from working on the code. While it is acceptable to do so for first-time reporters who don't know better, I'd expect project members who *know* that they need to create the issues in the right places.

**Issues about AppImageUpdate, linuxdeployqt, zsync, etc. need to be created in the appropriate issue trackers. Period.**

**Comment by KurtPfeifle** [comment]
> *"What exactly are you complaining about here?"*

Read again. I was not "complaining". I simply noticed something, which seemed odd at first look. And I wrote: *"Maybe you want to re-evaluate each case ..."*. Doesn't sound like a "complaint" to me. So if you re-evaluated and decided to close this issue because you think it is exactly as is intended: fine. You're the master of all trades, I'm only a stupid user trying to keep his eyes open.

**Comment by KurtPfeifle** [comment]
> P.S.: Sentences like
> 
> (NOT reporting this to the linuxdeployqt and AppImageUpdate projects for now...)
> 
> ... do you want to state that you're too lazy to report those issues in the right projects? It is an annoying task for maintainers to create the issues in the right projects (if there are any), that just keeps us from working on the code. While it is acceptable to do so for first-time reporters who don't know better, I'd expect project members who know that they need to create the issues in the right places.
>
> Issues about AppImageUpdate, linuxdeployqt, zsync, etc. need to be created in the appropriate issue trackers. Period.

Thanks again for another lecture.

I wrote "for now". This because I tried to avoid your repeated lecturing and because I wasn't sure if this was an issue at all. Believe it or not, I'd have been prepared to re-create the respective issues at the other locations in case of validity if I hadn't been so stupid as to create *this* issue in the first place.

**Comment by probonopd** [comment]
@KurtPfeifle this is directly related to the fact that some of the releases do include the version in the filename (most, as is recommended) but some don't (those that are frequently used by automated scripts as part of CI builds, such as `appimagetool` and `linuxdeployqt`).
