### ISSUE TITLE
Suggest you change edit permissions on your wiki

### ISSUE THREAD

**Issue by rspq** [AppImage/AppImageKit#644]
Someone had changed the Linus footer quote to "This is very dumb" (I set it back to "cool" just now). No need to be open to such silliness is there?

**Comment by TheAssassin** [comment]
The nature of Wikis is to be open for changes, so that anyone can contribute. Unfortunately, the GitHub Wikis can't be moderated, so we decided to open editing for everyone.

@probonopd what's your take on this?

@rspq thanks for notifying us. I will take actions on the change. This clearly violated GitHub's terms, and I hope GitHub will take actions accordingly.

**Comment by TheAssassin** [comment]
@rspq I've send a report of abuse to GitHub. I'll keep you up to date about this process.

**Comment by probonopd** [comment]
I think locking everyone out from editing the wiki would be too high a price to pay to avoid silliness like this. I'd like to avoid closing the Wiki down, but need to see how this continues. In any case, thanks for reporting.

**Comment by simoniz0r** [comment]
I would personally close them down and just accept PRs.  That change has been there for like a week now.

Either you should be monitoring it for changes if you have it open to be edited by everyone or just close the editing and accept PRs.  Too much potential for abuse if it's not going to be monitored closely.
