### ISSUE TITLE
Consider adding %F to all Exec= lines generated by appimaged if not already there

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#649]
According to https://github.com/Ultimaker/Cura/issues/2984 (on some desktops such as apparently elementary) the lack of `%F` prevents the application from being shown in the "open with" dialog. As shown above, it is working in other desktops without this (such as in XFCE).

I assume that many AppImages are lacking `%F` in the `Exec=` line of the desktop file; hence `appimaged` could simply always put it there if it is not there yet.

What do people think?

**Comment by davidmhewitt** [comment]
This isn't a very good idea.

What if it is an application that doesn't/can't open files via the command line? It will start appearing in the "open with" dialogs for GNOME, elementary and other desktop environments. And then will do nothing or crash when you try to make it open files.

Or, what if it really needed to be a `%U` argument there to indicate that it can only open URIs instead of an '%F'. You can't just make up a desktop file for the application and hope it works. It needs to be based upon the applications original desktop file, which you have to assume is correct.

**Comment by TheAssassin** [comment]
I agree to @davidmhewitt's opinion, I am strongly opposed to this, too.

It might be quite problematic to "force add" such a parameter to the `Exec=` lines, as many apps's option parsers are position sensitive, etc. Imagine linuxdeployqt for example. Apps like linuxdeployqt will take a file as a parameter, but this needs to be the first parameter, before all flags, etc. If you'd write a desktop file with additional parameters for such an app, and appimaged would make the desktop file pass a file parameter at a position the option parser won't like, the app wouldn't start at all.

Instead, I think since PR #643 appimaged appends parameters as the upstream author intended. Now, it's their responsibility to write a good desktop file, and I think that's the best we can do. There is no longer a cryptic bug that comes from appimaged "forgetting" parameters in the `Exec=` lines. If an application author forgets e.g., the `%F` parameter, they can just google for a solution, and when they add the parameter, it will "just work" as intended.
