### ISSUE TITLE
Package conflicts for AppImageKit

### ISSUE THREAD

**Issue by Alkaris** [AppImage/AppImageKit#766]
There's one issue I've come across while trying to run the `install-build-deps.sh` script for this AppeImageKit, and that it relies on `libpng12`, and so it doesn't seem to work when I have `libpng16` installed, libpng16 is revision 1.6 for the PNG Library and you can't really install the `-dev` packages for `libpng12` unless you remove `libpng16` ones instead. I really think you should be able to run and compile with `libpng16` dev packages, future versions and revisions of the PNG Library.

```
The following packages have unmet dependencies:
 libcairo2-dev : Depends: libfontconfig1-dev (>= 2.2.95) but it is not going to be installed
                 Depends: libfreetype6-dev (>= 2.1.10) but it is not going to be installed
                 Depends: libpng-dev
```

can't do install for `libcairo2-dev` unless I uninstall `libpng16-dev`, `libpng16-tools`, `libpng16-devtools` for `libpng12-dev`, which will only then allow me to install the other depends since they too depend on `libpng12-dev` it would kind of made more sense to instead use `libpng3` or `libpnglite-dev`. You do need something that will work with future packages.

**Comment by probonopd** [comment]
Thanks for your report @Alkaris. 
What are you trying to achieve in the end?

We distribute `appimagetool` and `appimaged` as AppImages and generally recommend to use the binaries we provide, unless you know exactly what you are doing. Especially for `appimagetool` it is _very_ important to build on an "old enough" build system (we use CentOS 6) in order not to introduce run-time dependencies on "too new" (read: newer than the oldest still-supported target distributions) libraries. Otherwise all AppImages produced by your own `appimagetool` may refuse to run on older systems.

For this reason, we are not interested in using build systems newer than CentOS 6 at the moment.

**Comment by TheAssassin** [comment]
@Alkaris we don't officially support Ubuntu bionic yet, package wise.

I've been reported a [similar issue](https://github.com/TheAssassin/AppImageLauncher/issues/28) in [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher/), where it took me a considerable amount of time to fix the issues. It involves building in a bionic Docker container, and having CMake change the dependency list depending on the OS. It's a lot more complex than I'd like it to be.

**Comment by probonopd** [comment]
Also, it would not be a good idea to build on bionic, since not only the resulting binaries themselves, but also AppImages produced with them would most likely not run on the oldest still-supported systems.

**Comment by TheAssassin** [comment]
@probonopd we should add a note somewhere about the incompatibility where it's visible.

**Comment by probonopd** [comment]
Yes. Maybe even in the software itself (refuse to run on "too new" systems until called with -force) or something like that.

**Comment by TheAssassin** [comment]
@probonopd we should rather inform people about this issue instead of putting barriers into the code.
