### ISSUE TITLE
Use multiarch

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#786]
When installing using `make install`, then instead of 

```
/usr/lib/appimagekit/runtime
/usr/lib/appimagekit/mksquashfs
```
we should probably use their [multiarch](https://wiki.debian.org/Multiarch/LibraryPathOverview) counterparts. (Not sure whether other distributions use different paths.)

**Comment by TheAssassin** [comment]
@probonopd your issue lacks a description explaining _why_ you consider this an issue. I don't see why there's an issue with this.

For packaging, the runtime shouldn't be needed, so we should perhaps make this a CMake option.

**Comment by probonopd** [comment]
I thought that currently 64-bit and 32-bit versions cannot be installed in parallel; which might cause a problem for distro packaging. But maybe I am wrong. I just noticed that `/usr/lib/` is relatively empty in Ubuntu while `/usr/lib/x86_64` is relatively busy.

**Comment by TheAssassin** [comment]
Installing more than one architecture of a package doesn't make any sense to me. You don't build packages for ARM on a x86 machine for example.

What you _actually_ want to do is add some kind of architecture to the path. But this is just compatible with Debian. RPM based systems often use paths like `/usr/lib64` etc.

I don't see _any_ use in installing appimagetool packages in parallel. The libappimage packages don't contain any of these files. And I don't want to maintain a list of these paths in order to install into the right place. This would also break our AppImage creation.

It's the distro maintainer's duty to fix these kinds of paths, not ours.

**Comment by probonopd** [comment]
> The libappimage packages don't contain any of these files.

Yes, I think this is what I had overlooked initially.
