### ISSUE TITLE
Make it possible to only compile libappimage

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#798]
Please make it possible to only compile libappimage with minimal dependencies being downloaded and needed by CMake.

Use case:
I as a developer want to use libappimage in my project. I don't care about the runtime, nor tests. I just want to consume libappimage, using as few build-time dependencies as possible, and for those that are neeeded, use as many distro-provided ones as possible. (To increase chances of anything that uses libappimage to ever be packaged in distros.)

**Comment by TheAssassin** [comment]
When building libraries from upstream sources, it makes sense to run its unit tests before continuing. You never know whether the source is stable (even if it is advertised so).
But actually, the "dependencies" you mention is a single Git submodule that needs to be fetched and doesn't really consume much space. When using CMake correctly (i.e., using `add_subdirectory(AppImageKit EXCLUDE_FROM_ALL)` to make sure only the things you `link` to are built), only the requested components are built. And I don't think having to install one or two dependencies you don't need because of platform checks is acceptable, too.

**Comment by probonopd** [comment]
Right now, trying to compile libappimage seemingly fails if things like xxd and so on are not available...

**Comment by TheAssassin** [comment]
> And I don't think having to install one or two dependencies you don't need because of platform checks is acceptable, too.

**Comment by probonopd** [comment]
> Did you check out my progress in the travis branch of your plugin project?

Err... must have missed it!

**Comment by probonopd** [comment]
Would it be possible to have 2 separate directories, one for libappimage (which needs to be built  first) and then a completely separate one containing runtime and appimagetool (which needs the other one built first)? Two completely decoupled CMake systems. So people who are only interested in the library would just build the former but not the latter.

**Comment by TheAssassin** [comment]
That doesn't seem really useful to me, @probonopd. I don't want to add a lot of maintenance overhead just because of two commands that need to be installed.

**Comment by probonopd** [comment]
OK, I don't know how distro packagers will think about this, but we'll see. cc @Conan-Kudo

**Comment by Conan-Kudo** [comment]
I'd actually rather build everything, after all, we can just subpackage out each built component so that at install time, you don't need everything.

**Comment by TheAssassin** [comment]
Closing as wontfix.
