### ISSUE TITLE
Portable Apps and their settings: Portable Home

### ISSUE THREAD

**Issue by pcx862** [AppImage/AppImageKit#883]
Hi, lead developer of [ORB Applications](https://www.orbital-apps.com/) here.

We have developed a "standard" called **[Portable Home](https://github.com/pcx862/orb-specification/issues/2)**, designed for the portability of data used by [Portable Apps](https://www.orbital-apps.com/portable).

I was wondering it there are plans to have "Portable AppImages" (Portable Apps)?
Is there interest in adopting something like this "standard"?

Nothing is set in stone regarding this standard, so it can be changed, if necessary.

Feel free to comment [on the Github page](https://github.com/pcx862/orb-specification/issues/2) or here.

**Comment by probonopd** [comment]
@JonasT we think that whether data should travel alongside the AppImage or not should be determined by the user, not the author of an AppImage.

**Comment by probonopd** [comment]
@pcx862 do you think all functionality is now in place and this ticket can be closed?
Please see https://docs.appimage.org/user-guide/portable-mode.html

**Comment by JonasT** [comment]
@probonopd I think that's a bad idea. This works fine for rather advanced linux users, but the average user expects to be able to download a "portable edition" without possibly screwing up the portability with manually creating directories. I think like this, the functionality is simply useless for a larger part of the userbase...

At the very least there would need to be a graphical dialog at launch to choose the mode. But that again would need a possible way *inside* the application to prompt for this

**Comment by probonopd** [comment]
You could put into your AppImage a custom AppRun script that would call

```
...
mkdir -p "${APPIMAGE}.home"
export HOME=${APPIMAGE}.home
....
```

I think. The downside is that the user can no longer decide.

**Comment by probonopd** [comment]
@JonasT do you have a concrete application in mind?

**Comment by JonasT** [comment]
Sure, this is e.g. a common problem with IDEs: it is often useful to ship programming language-specific flavors (special set of addons & settings), but if the user already has a system-wide install all the settings might be messed up and interfering, so it is vital to be able to offer such a flavored IDE as a portable application. IDEs are also the kind of app where users will be very not amused if the settings are botched up, since they're usually highly configured to personal needs.

Apart from that, any creative application which the user might want to use on the run and keep everything with them, and they would possibly end up disappointed if they discovered on the run they messed up making it portable and half the settings are gone. It's just better to be able to ship a clearly separate, clearly portable build that is always portable no matter what, so that such room for error is eliminated

**Comment by JonasT** [comment]
Is this something that is done inside the app image, or outside? Because if it can't be done inside without external scripts, it doesn't really help.

Also, there is always the use case for portable IDEs, portable audio editing apps, ... what have you, and for those the use case of "just give me a portable version I can't accidentally make not portable" always remains. I was just trying to give more specific examples since you asked for it, but I don't think those are super relevant for the general use case of an always-portable-no-matter-what version

**Comment by probonopd** [comment]
Inside.

Point is, you don't really need a portable "version", since every (recent) AppImage can be used in a "portable" way.

**Comment by JonasT** [comment]
You're not wrong, but depending on the target audience it's still useful to have an explicit portable version - but you made it abundantly clear that is possible to do, so that's good enough for me :+1: sorry for the comment spam

**Comment by probonopd** [comment]
Thanks @JonasT

**Comment by droped** [comment]
Say I have a folder next to my appimage called program.appimage.home.config

Will it store both config and the home directory files there, neither or only one? Or do I simply not need it?

**Comment by TheAssassin** [comment]
If your AppImage is called `a.AppImage`, you can create the directories `a.AppImage.home` and/or `a.AppImage.config`. The former should include configuration files. You should probably test this, though, as these are experimental features.

**Comment by droped** [comment]
So technically only .home should be necessary?

**Comment by TheAssassin** [comment]
It highly depends on the application. In theory, as long as the application references everything from `$HOME`, I'd say yes. But you should really test this.

**Comment by droped** [comment]
Ok, so far, no appimage has misbehaved without the .config folder (as in, none has written outside of the .home folder unless specified). Thank you.

**Comment by TheAssassin** [comment]
There is the [XDG base dir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), which most frameworks support. But you cannot predict the environment variables on a system, and there are implementation specific details. Therefore, these directories are considered experimental, as they do not attempt to make guarantees but are a best effort solution.
