### ISSUE TITLE
Builds do not get uploaded to GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#905]
https://travis-ci.org/AppImage/AppImageKit/jobs/478431582#L3838

> Release uploading disabled for pull requests

cc @TheAssassin

**Comment by TheAssassin** [comment]
Interesting. We've recently switched to the `master` branch naming wise. There was a bug in the Travis config preventing us from building at all, see https://github.com/AppImage/AppImageKit/commit/5bffa45db35f23990b7848f0122f60671e4e9afa.

The issue here is the hardcoded branch name in https://github.com/AppImage/AppImageKit/blob/master/.travis.yml#L39. Will fix that asap.

@probonopd uploadtool should very soon implement https://github.com/probonopd/uploadtool/issues/30 to make this workaround obsolete.

**Comment by probonopd** [comment]
Thanks for fixing it short-term.

**Comment by TheAssassin** [comment]
I broke it, after all...
