### ISSUE TITLE
Opening an URL from inside an AppImage fails

### ISSUE THREAD

**Issue by Fulgen301** [AppImage/AppImageKit#922]
Similar to the closed issue #124, invoking the browser with `QDesktopServices::openUrl` from an AppImage fails (Fulgen301/LCEdit@3fd7873b088e0a34d12aefeb185649aa8062048d). However, launching `xdg-open` via `QProcess::execute("xdg-open", { url })` also doesn't do anything (besides being an ugly workaround). Given that `QDesktopServices::openUrl` returns `true`, I can't catch this case either.

**Comment by probonopd** [comment]
Do you have any idea why it fails? Maybe run with `strace` to see what's going on.

**Comment by TheAssassin** [comment]
More of an issue for linuxdeployqt.

**Comment by Fulgen301** [comment]
It seems I was just running an earlier built AppImage without said commit, it works now, sorry for wasting time.

**Comment by bikrambox** [comment]
> Similar to the closed issue #124, invoking the browser with `QDesktopServices::openUrl` from an AppImage fails ([Fulgen301/LCEdit@3fd7873](https://github.com/Fulgen301/LCEdit/commit/3fd7873b088e0a34d12aefeb185649aa8062048d)). However, launching `xdg-open` via `QProcess::execute("xdg-open", { url })` also doesn't do anything (besides being an ugly workaround). Given that `QDesktopServices::openUrl` returns `true`, I can't catch this case either.






**Just solved it.** 


**Create a  [Appname.desktop]** file first remember this is the same as creating **Desktop** entries but for the sake of the issue here just create it in the same folder, Next, we will edit it using any editor or terminal and the content be like
--------------------------------------------------------------------------------
#!/usr/bin/env xdg-open

[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Figma
Exec=/home/firedrake/figma-linux-0.7.1.AppImage %u
Icon=signal-desktop
MimeType=x-scheme-handler/figma;
--------------------------------------------------------------------------------

**Very simple -->** **ICON** be anything you want; Name: anything you want; Exec is the key; The LOC of the image file and obviously after making it executable and test that it's running and then adding the **%u** at the end then save it, 
I tried making a **URI handler** but didn't work for me, this was the best way I have come through.  Try it.

and then you can easily export it to the 

ln -s /var/lib/snapd/desktop/applications/codium_codium.desktop **/home/firedrake/.local/share/applications**
--------------------------------------------------------------------------------
/var/lib/snapd/desktop/applications/codium_codium.desktop    -----> **my app location and**

/home/firedrake/.local/share/applications ---> Desktop entry location
--------------------------------------------------------------------------------
OS: Kali linux.
--------------------------------------------------------------------------------
application folder! using this little comment.

**Comment by sysfu** [comment]
> > Similar to the closed issue #124, invoking the browser with `QDesktopServices::openUrl` from an AppImage fails ([Fulgen301/LCEdit@3fd7873](https://github.com/Fulgen301/LCEdit/commit/3fd7873b088e0a34d12aefeb185649aa8062048d)). However, launching `xdg-open` via `QProcess::execute("xdg-open", { url })` also doesn't do anything (besides being an ugly workaround). Given that `QDesktopServices::openUrl` returns `true`, I can't catch this case either.
> 
> **Just solved it.**
> 
> ## **Create a [Appname.desktop]** file first remember this is the same as creating **Desktop** entries but for the sake of the issue here just create it in the same folder, Next, we will edit it using any editor or terminal and the content be like
> #!/usr/bin/env xdg-open
> 
> ## [Desktop Entry]
> Version=1.0
> Terminal=false
> Type=Application
> Name=Figma
> Exec=/home/firedrake/figma-linux-0.7.1.AppImage %u
> Icon=signal-desktop
> MimeType=x-scheme-handler/figma;
> **Very simple -->** **ICON** be anything you want; Name: anything you want; Exec is the key; The LOC of the image file and obviously after making it executable and test that it's running and then adding the **%u** at the end then save it, I tried making a **URI handler** but didn't work for me, this was the best way I have come through. Try it.
> 
> and then you can easily export it to the
> 
> ## `ln -s /home/firedrake/.local/share/applications/Figma.desktop /home/firedrake/.local/share/applications`
> /home/firedrake/.local/share/applications/Figma.desktop -----> **my app location**
> 
> /home/firedrake/.local/share/applications ---> Desktop entry location
> 
> Now, after creating and able to launch the app using desktop entry now time to work at grabbing the **TOKEN**, #Note: Desktop entry should be in the Application folder by now, Next, There in the same folder you will find a `mimeinfo.cache` file Edit using your Editor and then create a new entry for the URI handler (i.e Fallback to the app) in my case, I created this.
> 
> ## `x-scheme-handler/figma=Figma.desktop;`
> ## `x-scheme-handler ` ----> this is just systemwide code, but **figma** is the focus here, when you see the error of xdg-open cannot find the specified location. you'll see **figma:.......................SECRET ..and something.........** Yes we grabbed that **figma** handle and forwarding it to the Figma.desktop and as you know Figma.desktop contains the `Figma %u `tag it'll grab it and Voila!
> it works
> ## OS: Kali Linux.
> using these little lines have fun.

This helped me to resolve a similar issue getting the DeltaChat Desktop Appimage to open links, thank you.
