### ISSUE TITLE
AutoUpdater creates the update.AppImage file instead of replacing it 

### ISSUE THREAD

**Issue by hugetiny** [AppImage/AppImageKit#926]
related issue: https://github.com/electron-userland/electron-builder/issues/3639
Can AutoUpdater replace the old file instead of create a update.AppImage file?

**Comment by probonopd** [comment]
What is AutoUpdater? I think you are referring to a feature of electron-builder that is unrelated to AppImageKit and the AppImage native way of updating, [AppImageUpdate](https://github.com/AppImage/AppImageUpdate). electron-builder uses its own way of updating in order to be consistent with what they are using for Windows.

General remark: Unlike with traditional package managers, AppImage provides the advantage that you can run multiple versions on the same system alongside each other. To take full advantage of this, the user should be asked whether they want to keep the original (old) version after a successful update; deleting it should be opt-in. Personally I don't like self-updating applications because I only ever update an application if I have issues with the old one or want to take advantages of new features, in which case I want to thoroughly test the new version before considering to remove the old version.

Discussion continues in https://github.com/electron-userland/electron-builder/issues/3639.

**Comment by TheAssassin** [comment]
AppImageUpdate has options (also in the API) to remove the original file after a successful update, and rename the new file.

**Comment by hugetiny** [comment]
@TheAssassin Where can i set the options to remove the original file ?

**Comment by TheAssassin** [comment]
@hugetiny depends on what you want to do. A general description was provided in https://github.com/AppImage/AppImageKit/issues/926#issuecomment-464309074.
