### ISSUE TITLE
appimagetool segfaults

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#934]
According to https://gitlab.com/inkscape/inkscape/commit/eadce286758e292efa59a53ef0aefbf885a5d19c#note_148472603,

> The appimage build started to fail with this commit due to a SEGFAULT, pipeline for 3711d5d7 was still working.
As nothing related to appimage was changed in between, I suspect this is due to an update of appimagetool from
`appimagetool, continuous build (commit cddcc2e), build 2034 built on 2019-01-22 15:01:38 UTC`
to
`appimagetool, continuous build (commit 7d45aa3), build 2046 built on 2019-02-11 22:41:20 UTC`

Many other projects are affected by this issue as well.

References:
* https://github.com/probonopd/linuxdeployqt/issues/355
* https://gitlab.com/inkscape/inkscape/commit/eadce286758e292efa59a53ef0aefbf885a5d19c#note_148472603

**Comment by probonopd** [comment]
As I have not made any changes recently, could @TheAssassin and @azubieta please have a look at this? Thanks.

**Comment by probonopd** [comment]
To reproduce:

- Clone https://github.com/probonopd/leocad/tree/patch-1 and try to build patch-1 on Travis CI
- See it crash: https://travis-ci.com/probonopd/leocad/builds/103791807#L945

**Comment by azubieta** [comment]
I tried to reproduce this issue locally. It happens that "appimagetool" is not the one that `segfault` but "linuxdeployqt". I guess that "linuxdeploy" had been tested enough like to recommend it as default tool.

**Comment by probonopd** [comment]
> It happens that "appimagetool" is not the one that segfault but "linuxdeployqt". 

How do you know?

**Comment by azubieta** [comment]
> How do you know?
...
> I tried to reproduce this issue locally
Basically ran `linuxdeployqt` until it segfault then manually run `appimagetool` which didn't `segfault`. But it do reported an error about a missing icon file.

**Comment by probonopd** [comment]
Not sure whether that proves that it is `linxudeployqt` which is segfaulting. Couldn't it be that appimagetool is segfaulting, depending on some random state (e.g., in some cases the same `appimagetool` seems to segfault when invoked from [linuxdeployqt](url) but not segfault if invoked directly)?

**Comment by probonopd** [comment]
What we could do is temporarily embed a build of `appimagetool` from early January into a recent `linxudeployqt` AppImage and see if the issues go away.

**Comment by probonopd** [comment]
Here is the proof that indeed it is `appimagetool` (or something it consumes, like `libappimage`) that is faulty:

https://travis-ci.com/probonopd/leocad/builds/103792983 now builds "green" without segfaulting after I have restarted the build that was building "red" before, this time with the latest `linuxdeployqt` that contains an older build of `appimagetool`: https://github.com/probonopd/linuxdeployqt/commit/d59e58356a8cb1bd8649a7c3857afa7d5ae6feee

**Comment by azubieta** [comment]
Maybe is neither `appimagetool` nor `linuxdeployqt` but the integration between them.

**Comment by probonopd** [comment]
Using the older `appimagetool` makes it work...

**Comment by TheAssassin** [comment]
> What we could do is temporarily embed a build of appimagetool from early January into a recent linxudeployqt AppImage and see if the issues go away.

Good that we store most of our artifacts `</self-praise>`.

Instead of guessing, please try to narrow down the range in which the breaking commit lays as much as possible, @probonopd. Then we will have a look at what's going on.

**Comment by probonopd** [comment]
> Good that we store most of our artifacts </self-praise>.

Indeeed!

I am doing a bisect now.

- https://artifacts.assassinate-you.net/artifactory/AppImageKit/travis-2009/appimagetool-x86_64.AppImage = good

**Comment by probonopd** [comment]
Do you know why my latest commit does not build @TheAssassin?

**Comment by TheAssassin** [comment]
Because of unresolved Git merge conflicts? https://travis-ci.org/AppImage/AppImageKit/jobs/507432949#L3030

Please stop your experiments on `master` and move them to a branch.

**Comment by probonopd** [comment]
Sometimes `git` is less smart than I expect it to be. In any case, my policy is that master must always be in good shape and if it is not, one needs to fix or revert until it is.

**Comment by TheAssassin** [comment]
Might be, but your commit orgy will be better on a branch and in a PR. The mess in our master branch could be avoided that way. And we could clean up the branch and make it pretty before merging, even if you personally are not so great with the CLI. Whatever is on master will always ever remain there, it can't be changed any more.

**Comment by probonopd** [comment]
That's true. Normally I work in branches, but in this case `linuxdeployqt` pulls stuff from continuous... I didn't want to rely on transfer.sh which is broken half of the time. Going forward, I think a monorepo would solve this kind of issues elegantly.

**Comment by probonopd** [comment]
https://travis-ci.com/probonopd/leocad/builds/103792983 still fails. I am really puzzled now. 

What we know so far:
* probonopd/linuxdeployqt@9cc80e5, https://artifacts.assassinate-you.net/artifactory/AppImageKit/travis-2034/appimagetool-x86_64.AppImage = good
* probonopd/linuxdeployqt@07a4f12, https://artifacts.assassinate-you.net/artifactory/AppImageKit/travis-2035/appimagetool-x86_64.AppImage = BAD

Reverting a9f2597 seems __not__ to have resolved this.

Any ideas? This whole episode would imho be avoidable if we had a [monorepo](https://github.com/AppImage/AppImageKit/issues/931) - then we would just roll back to the point where it still worked, done.

**Comment by TheAssassin** [comment]
Instead of randomly reverting one should instead use the information what commit is broken for debugging.

Please stop annoying us with this monorepo bullshit (it _is_, especially in OSS): we have an issue where the rest of the devs said it's a horrible idea. There's no need for framing in issues that don't have anything to do with this.

**Comment by probonopd** [comment]
Here is what I have found out so far:

* https://artifacts.assassinate-you.net/artifactory/AppImageKit/travis-2034/appimagetool-x86_64.AppImage was the last working
* Since 2035 we get segfaults when being invoked from linuxdeployqt
* Build log of 2035: https://travis-ci.org/AppImage/AppImageKit/builds/487703234/
* The commit was: "Increase robustness of git commit version guessing"
* I tried to revert that commit, but it still segfaults
* So something else must have changed beginning with build 2035
* But I don't know what

**Comment by TheAssassin** [comment]
Just from looking at the code, might be https://github.com/AppImage/AppImageKit/commit/a9f25977d22db3c69a377e40a1bfdeac35330c84#diff-22b5078e6286ae2bb4ef0316fd695255R580? Right now, the master is quite borked and I don't have time to properly debug on a branch, so that will have to wait until tonight.

**Comment by probonopd** [comment]
* Made branch `last-good` from cddcc2e and built it: https://travis-ci.org/AppImage/AppImageKit/builds/507462540
* Used this for linuxdeployqt: https://github.com/probonopd/linuxdeployqt/commit/b6aafc2236c0983a2506ea6e6e00374b7110c74d
* LeoCAD build _succeeds_ without segfault: https://travis-ci.com/probonopd/leocad/builds/103792983 `appimagetool, continuous build (commit cddcc2e), build 2052 built on 2019-03-17 12:49:07 UTC`

So, branch `last-good` is indeed working. `master` is currently broken.

Normally I would now roll back `master` to the state of `last-good`.

**Comment by TheAssassin** [comment]
PR sent: #937

**Comment by probonopd** [comment]
To make master work again, I will soon change the name of `master` to `broken`, and change the name of `last-good` to `master` and make this the default branch.

master always must be in a good state. Unfortunately this means that all changes made after Jan 22, 2019 need to be ported over.

Unless someone has a better idea. I am not a git wizard but this is in accordance to my general polity of reverting to the last know good version when master is broken for too long.

**Comment by TheAssassin** [comment]
That's not reverting, that's breaking everyone's local git checkouts. That's the big problem here, and why reverting using `git revert` is annoying but required to not break things.

The problem is that nobody but you has these issues making AppImages. The branch builds fine. Your definition of broken is quite uniliteral, and your bug is hard to grasp since noone can reliably reproduce it. 

IMO, the right way to make things segfault-free is to merge my PR since it fixes all reproducible segfaults in `master`. Have you tried the builds in there recently?

We need to rewrite this tool sooner than later...

**Comment by probonopd** [comment]
It breaks lots of downstream users' builds, including Inkscape and LeoCAD's.

It can be reliably reproduced by cloning LeoCAD's GitHub repository, and changing it so that it uses a different `linuxdeployqt` that uses the `linuxdeployqt` version under test.

**Comment by probonopd** [comment]
> We need to rewrite this tool sooner than later...

"Bugfix and continuously improve" is appreciated, "throw away and make something similar but not quite" is something I am increasingly allergic against.

**Comment by TheAssassin** [comment]
> "Bugfix and continuously improve" is appreciated, "throw away and make something similar but not quite" is something I am increasingly allergic against.

You can't "bugfix" if you want to rewrite a tool in another language (C++), and if I rewrite all components _anyway_ with a proper software design, then I don't call this "continuously improve".

**Comment by probonopd** [comment]
Who says `appimagetool` needs to to be written in another language? Not me...

All I use linuxdeployqt for is through Travis CI and GitLab CI. So I can't comment about other use cases as I don't really care about them.

**Comment by TheAssassin** [comment]
All we want is to improve the code base and make things easier, not more complex. We want to foster reusability, too. Therefore, the idea is to, some day, make a libappimagekit (which implements all the basics you need to build AppImages in different modules which are small units of code that can be unit-tested and also are easier to maintain) and define the workflow by combining these so-called primitives. Then we build a frontend appimagetool which only has to care about argument parsing and the rest will be handled in that lib.

Clear advantages:
 - the ability to test _at all_ (right now, this is not possible; not saying there aren't other ways, though)
 - the design "library + frontend" is very powerful and has proven useful in linuxdeploy and its plugins
 - by using C++, we can avoid/hide most pointer handling properly, i.e., the software design can actively prevent segfaults and doesn't constantly have to fix those
 - there's much better and full-of-features software libraries available (e.g., boost (boost::filesystem is _really_ helpful))
 - other software can implement AppImage making on an ABI level (this won't be needed by us and also won't be officially supported since we want people to use the latest and greatest appimagetool; but hey, it's cool to have)

This is not an urgent project, but it should eventually be done. The way you would suggest is probably to break up the current code, move it into modules etc., but the current code base is so tightly bound so there would be the work of having to move the code plus all the rewriting which would anyway happen to make things modular. Therefore, I'm pushing towards rewriting it completely, as that'll save time and will be more fun to develop, too.

**Comment by probonopd** [comment]
Looks like we are good, the segfault seems gone. Thanks @TheAssassin.

Regarding using C++ for `appimagetool`, this needs to be discussed separately.

**Comment by TheAssassin** [comment]
Sure. By the way, regarding discussions, I've sent you a mail and I'm kind of "in need of feedback".
