### ISSUE TITLE
Version guessing broken

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#942]
The latest Inkscape continuous builds no longer have the git commit hash as part of the filename, despite https://gitlab.com/inkscape/inkscape/blob/master/packaging/appimage/generate.sh not having changed.

https://gitlab.com/inkscape/inkscape/-/jobs/183132465/artifacts/file/Inkscape-beb7fdf-x86_64.AppImage still had the correct file name 4 days ago.

Could this have to do with the reshuffling in https://github.com/AppImage/AppImageKit/commit/9cfa7b6585d97bba6106ea3005f7cfbcb9a6251e @TheAssassin?

**Comment by TheAssassin** [comment]
You know C, so you tell me. I don't see any reason why this should be the case. Workflow wise it's just above the rest of the packaging...

**Comment by TheAssassin** [comment]
Can you provide a log?

**Comment by probonopd** [comment]
Also broken here:
https://github.com/probonopd/btx_decoder/releases

Log:
https://api.travis-ci.com/v3/job/189010751/log.txt

I suspect it has to do with 9cfa7b6 @TheAssassin because this was a recent change regarding version guessing, and since then it is broken.

**Comment by TheAssassin** [comment]
I read the log, this specific commit is *not* the issue here. It's GLib again, but I now know where the bug is.
It's pretty obvious when you read the bug that this moving-the-code is not the breakage here, it's the GLib version we linked appimagetool to. There must be a bug in it.

> Failed to run 'git rev-parse --short HEAD, but GLib says the process didn't exit abnormallyFailed to run 'git rev-parse --short HEAD, but failed to interpret GLib error state: 0

There's that ["error interpretation method"](https://developer.gnome.org/glib/stable/glib-Spawning-Processes.html#g-spawn-check-exit-status) basically disagrees with [`g_spawn_command_line_sync`](https://developer.gnome.org/glib/stable/glib-Spawning-Processes.html#g-spawn-command-line-sync). This should never happen. I'm looking through the changelogs there to see whether there is a bug known and whether we can just upgrade GLib.

**Comment by probonopd** [comment]
Argh. this is our way over my head, I understand only 50%, but I would like things to be back in a working state. Thank you very much for your investigation and for fixing this

**Comment by TheAssassin** [comment]
Does it work now? I've pushed a fix earlier.

**Comment by probonopd** [comment]
How did you test the version guessing on Travis CI? It looks to me as if it is still broken.

**Comment by probonopd** [comment]
What is the best way to get the repository back into the state as it was at a certain commit?

**Comment by TheAssassin** [comment]
@probonopd define "looks broken to me".

I already explained it multiple times: you *can't* do this in Git, you would break everyone's repositories. The only way is to revert *every* commit. And that's even worse, since it creates tens of commits which then in the end have to re-reverted to get back.

This is the huge issue when binding yourself to such crappy infrastructure like Travis and implement all this kind of guessing and stuff: it just doesn't work reliably, it's impossible to test outside there, and only causes headaches...

Same goes for this annoying appimagetool-now-needs-categories-although-that's-not-required-from-the-standard. If I rebuild older commits, things break because of this breaking change:

```

Running command: /tmp/linuxdeploy-plugin-appimage-build-RpUKvz/AppDir/usr/bin/appimagetool "AppDir" "-u" "gh-releases-zsync|linuxdeploy|linuxdeploy-plugin-appimage|continuous|linuxdeploy-plugin-appimage-x86_64.AppImage"
appimagetool, continuous build (commit 915b76d), build 2071 built on 2019-03-30 11:58:01 UTC
WARNING: appstreamcli command is missing, please install it if you want to use AppStream metadata
Categories entry not found in desktop file
.desktop file is missing a Categories= key
```

Argh!

**Comment by probonopd** [comment]
Please do all tests exclusively on Travis CI as that is the environment most of our users will use (also GitLab CI).
Local builds are not worth much.

All my logs are online...

**Comment by probonopd** [comment]
It worked until January, btw.

**Comment by TheAssassin** [comment]
Local builds are perfectly worth everything, as they can be *debugged*. Whereas Travis CI builds can not. I always said this whole version guessing is a bad idea and shouldn't be put into appimagetool...

Works fine by the way: https://travis-ci.org/TheAssassin/appimagetool-mwe/builds/513506028#L466

**Comment by Calinou** [comment]
I'm of the opinion version parsing should be left to the implementer anyway.

**Comment by probonopd** [comment]
Check this @TheAssassin:
https://travis-ci.com/probonopd/btx_decoder/jobs/189041700#L784

**Comment by probonopd** [comment]
Looks like this very error was addressed in https://github.com/AppImage/AppImageKit/commit/915b76dd0fb47fa17505f5dcf524eebae0e77edd, rebuilding `linuxdeployqt` now so that I can re-run the test.

**Comment by probonopd** [comment]
Works again. Thank you @TheAssassin

**Comment by TheAssassin** [comment]
> I think setting version identifiers should be left to the implementer anyway.

Yeah, git commits don't make for very good versions. They're just useful to distinguish two different versions of a tool. But incremental numbers (e.g., Travis or other CI build number) are much better, as they also allow one to compare between newer and older builds, etc.

**Comment by probonopd** [comment]
It's better to `export VERSION=...` prior to running `appimagetool`.
