### ISSUE TITLE
[electron-builder] desktop file error in TryExec line when path has spaces

### ISSUE THREAD

**Issue by axelmeunier** [AppImage/AppImageKit#948]
When there is a space in one of the folders's name in the path, the desktop file automatically generated upon first run when enabling desktop integration has the correct Exec line but an incorrect TryExec line.
Example for Gimp 2.99 AppImage (but it is confirmed with other AppImages as well):
```
Exec="/home/axel/Linux stuff/Applications/GIMP_AppImage-git-2.99.1-20190328-x86_64.AppImage" %U
TryExec=/home/axel/Linux\\sstuff/Applications/GIMP_AppImage-git-2.99.1-20190328-x86_64.AppImage
```
Removing the extra `"\"` in the TryExec line solves the issue.

**Comment by TheAssassin** [comment]
@axelmeunier AppImageKit is about making AppImages, and has nothing to do with desktop integration. What tool do you use for integration? We need to move the issue there, then we can also analyze it further.

**Comment by axelmeunier** [comment]
Sorry if i did not report at the right place. I don't use a tool for integration. When first running some Appimages (e.g. Etcher, Gimp, Kdenlive), the user is asked if they want to enable the creation of a desktop file. I thought it was a feature implemented when making the AppImage, hence why I reported here. Kindly advise where to report.

**Comment by TheAssassin** [comment]
Urgh. *Not that again!*

It's an antipattern to embed this dialog, if you ask us. That script isn't maintained at all, so please don't expect fixes from us.

We do not recommend to put any such tools inside the AppImages. It's redundant bloat, impossible to update (interoperability etc.), doesn't support multiple versions, ...

I'd recommend you to install AppImageLauncher or appimaged to manage desktop integration.

**Comment by axelmeunier** [comment]
Ok I understand - I'll try to install one of those tools (as I am using Solus I think I have to compile myself...)
I am sorry, I don't know the whole history of AppImage and good practices for making AppImages... I am just a normal user encountering a bug and trying to report it 😀
So I guess I have to report to the different AppImages that still use this script :)
Thanks and keep up the good work.

**Comment by TheAssassin** [comment]
That rant doesn't go into your direction. It's the people who haven't removed that dialog yet. Electron even _want_ this, they do not want to drop it.

Thanks for the kind words!

**Comment by axelmeunier** [comment]
Yes i got it, no big deal :)

**Comment by probonopd** [comment]
You can use `systemIntegration: "doNotAsk"` which should be the default in our opinion (but isn't).

https://www.electron.build/configuration/appimage.html

**Comment by develar** [comment]
I have no idea how to fix `${APPIMAGE// /\\s}`, because `\s` will be just `s`, and `\\s` for some reasons now (reproduced for ubuntu 18) translated as `\\s`. So, I decided to to remove `TryExec`.

@TheAssassin @probonopd electron-builder uses AppImage as an universal format. Standalone executable binary. Forcing using `appimaged`... is kind of controversial, because in this case better to use "native" formats like snap/flatpack (as support is preinstalled already on a user machine).

Maybe, electron-builder AppImage should somehow promote `appimaged` to be installed (and install it as part of executable)... but I am sure that AppImage executable without desktop integration  is no go way, because who will explain for user how to install it and what's required?

**Comment by TheAssassin** [comment]
Again, @develar, the problem is that this outdated desktopintegration stuff is incompatible with all the real systems, lacks most of the features and also isn't portable at all. Removing `TryExec` makes things even worse, that means AppImages which disappear leave broken desktop files on the system.

**Comment by develar** [comment]
@TheAssassin Should electron-builder asks to install https://github.com/TheAssassin/AppImageLauncher? (on https://appimage.org/ I see nothing about desktop integration on first glance).

**Comment by develar** [comment]
Whooo... I missed AppImageLauncher. I think it is will be probably ok to completly remove desktop integration script in electron-builder and do nothing. Probably if user wants desktop integration, he will be able to find out AppImageLauncher. And in any case no one can blame me now, since for angry developers (producer of app) I can always answer "use snap or ask AppImage authors". 

Initially, electron-builder was implemented in this way not because I want to contradict your position, but simply because it was so when integration was implemented. Now, you changed your way, and I think it will be good for all if electron-builder will be aligned to AppImage ecosystem.

**Comment by TheAssassin** [comment]
We're in the process of migrating everything to AppImageLauncher, so that might be a good idea. We definitely need better documentation on that, you're absolutely right, I opened an issue [here](https://github.com/AppImage/AppImageKit/issues/973).
