### ISSUE TITLE
LibUSB on appimage blacklist

### ISSUE THREAD

**Issue by cculianu** [AppImage/AppImageKit#971]
HI,

We use libusb for our project (https://github.com/Electron-Cash/Electron-Cash) to support various hardware devices via USB.

I was wondering why libusb is on the blacklist?

We end up copying it back to the appdir manually anyway right after it gets deleted by the blacklist code.

I was wondering if you would consider removing it form the blacklist or if not -- can you tell me why it's blacklisted?

I searched this repository and couldn't find the discussion or reason so I am curious.

Thanks in advance.

**Comment by EchterAgo** [comment]
We had a problem on some systems with crashing where the system `libusb` was loaded but this in turn loaded the `libudev` from the AppImage. This caused a crash in the dynamic linker relocation code. We have included `libusb` into our AppImage because of this. We also widely tested this AppImage on multiple distributions and found no issues. From what I can tell `libusb` should be usable independent of kernel version.

https://github.com/Electron-Cash/Electron-Cash/commit/25d45fdcbfa335d83de876ff16e978a058d17e22

**Comment by cculianu** [comment]
Oops. Wrong repo.  This belongs in `pkg2appimage`. My bad! Will close and re-create there...

**Comment by cculianu** [comment]
Re-opened this issue here: https://github.com/AppImage/pkg2appimage/issues/378

**Comment by probonopd** [comment]
Answered there.
